var group__dispatcher__api =
[
    [ "Alias Function API", "group__alias__function__api.html", "group__alias__function__api" ],
    [ "Attachment Function API", "group__attach__function__api.html", "group__attach__function__api" ],
    [ "Autocrypt Function API", "group__autocrypt__function__api.html", "group__autocrypt__function__api" ],
    [ "Compose Function API", "group__compose__function__api.html", "group__compose__function__api" ],
    [ "Preview Function API", "group__preview__function__api.html", "group__preview__function__api" ],
    [ "Envelope Function API", "group__envelope__function__api.html", "group__envelope__function__api" ],
    [ "Global Function API", "group__global__function__api.html", "group__global__function__api" ],
    [ "History Function API", "group__history__function__api.html", "group__history__function__api" ],
    [ "Index Function API", "group__index__function__api.html", "group__index__function__api" ],
    [ "Menu Function API", "group__menu__function__api.html", "group__menu__function__api" ],
    [ "Gpgme Function API", "group__gpgme__function__api.html", "group__gpgme__function__api" ],
    [ "Pgp Function API", "group__pgp__function__api.html", "group__pgp__function__api" ],
    [ "Smime Function API", "group__smime__function__api.html", "group__smime__function__api" ],
    [ "Pager Function API", "group__pager__function__api.html", "group__pager__function__api" ],
    [ "Pattern Function API", "group__pattern__function__api.html", "group__pattern__function__api" ],
    [ "Postpone Function API", "group__postpone__function__api.html", "group__postpone__function__api" ],
    [ "Sidebar Function API", "group__sidebar__function__api.html", "group__sidebar__function__api" ],
    [ "alias_function_dispatcher", "group__dispatcher__api.html#ga0bcc447d78a52092001d46b595f0392f", null ],
    [ "attach_function_dispatcher", "group__dispatcher__api.html#ga539d9c120b47828fd817a448232d3ac5", null ],
    [ "autocrypt_function_dispatcher", "group__dispatcher__api.html#ga76f9e39b416ed48f57de3daa209937dc", null ],
    [ "compose_function_dispatcher", "group__dispatcher__api.html#ga571bdfae653f28d99f1428a8e4ece8a9", null ],
    [ "preview_function_dispatcher", "group__dispatcher__api.html#gab28bd6250266058c4b6357b685c5828b", null ],
    [ "enter_function_dispatcher", "group__dispatcher__api.html#ga49aac7d6f001dce4953fc7c5f8534192", null ],
    [ "env_function_dispatcher", "group__dispatcher__api.html#gabe0552d21dc94df02312f485807b3fa2", null ],
    [ "global_function_dispatcher", "group__dispatcher__api.html#gac7fdd018d82bde8b5b89be1f2af9a74e", null ],
    [ "history_function_dispatcher", "group__dispatcher__api.html#gaf0e30e9fad71050e69a048c87f900b37", null ],
    [ "index_function_dispatcher", "group__dispatcher__api.html#gab4c6e64de62f0f914b428b29d4bd3b32", null ],
    [ "menu_function_dispatcher", "group__dispatcher__api.html#gad454afae4ce796a49a888da9d0fe6a2b", null ],
    [ "menu_tagging_dispatcher", "group__dispatcher__api.html#gaba2973f42737d632b376733a5ab9edec", null ],
    [ "gpgme_function_dispatcher", "group__dispatcher__api.html#ga07cc5849d7a417eaf4be3e9227a3aa82", null ],
    [ "pgp_function_dispatcher", "group__dispatcher__api.html#gabd928ae781004cc11a353ec31c4e4542", null ],
    [ "smime_function_dispatcher", "group__dispatcher__api.html#ga927ed196f3974adce6165467a818d5d8", null ],
    [ "pager_function_dispatcher", "group__dispatcher__api.html#ga265e1256bb004b6ccd1b0fd1df2709be", null ],
    [ "pattern_function_dispatcher", "group__dispatcher__api.html#ga645af1f2a6ddb7da36f6f9318611e07d", null ],
    [ "postpone_function_dispatcher", "group__dispatcher__api.html#ga66da9a90370f895fef3473b7b4b99774", null ],
    [ "sb_function_dispatcher", "group__dispatcher__api.html#ga05923dea014c9fa45e7f82abb224ab0a", null ]
];