var lib_ncrypt =
[
    [ "Config used by libncrypt", "ncrypt_config.html", null ],
    [ "Signing/encryption multiplexor", "ncrypt_crypt.html", null ],
    [ "Wrapper for PGP/SMIME calls to GPGME", "ncrypt_crypt_gpgme.html", null ],
    [ "Register crypto modules", "ncrypt_crypt_mod.html", null ],
    [ "Wrappers for calls to CLI PGP", "ncrypt_crypt_mod_pgp.html", null ],
    [ "Wrappers for calls to GPGME PGP", "ncrypt_crypt_mod_pgp_gpgme.html", null ],
    [ "Wrappers for calls to CLI SMIME", "ncrypt_crypt_mod_smime.html", null ],
    [ "Wrappers for calls to GPGME SMIME", "ncrypt_crypt_mod_smime_gpgme.html", null ],
    [ "Wrapper around crypto functions", "ncrypt_cryptglue.html", null ],
    [ "GPGME Key Selection Dialog", "ncrypt_dlg_gpgme.html", null ],
    [ "PGP Key Selection Dialog", "ncrypt_dlg_pgp.html", null ],
    [ "SMIME Key Selection Dialog", "ncrypt_dlg_smime.html", null ],
    [ "Ncrypt Expando definitions", "ncrypt_expando_command.html", null ],
    [ "Ncrypt Expando definitions", "ncrypt_expando_gpgme.html", null ],
    [ "Ncrypt Expando definitions", "ncrypt_expando_pgp.html", null ],
    [ "Ncrypt Expando definitions", "ncrypt_expando_smime.html", null ],
    [ "PGP/Smime functions", "ncrypt_functions.html", null ],
    [ "Parse the output of CLI PGP program", "ncrypt_gnupg.html", null ],
    [ "Gpgme functions", "ncrypt_gpgme_functions.html", null ],
    [ "Definition of the Ncrypt Module", "ncrypt_module.html", null ],
    [ "PGP sign, encrypt, check routines", "ncrypt_pgp.html", null ],
    [ "Pgp functions", "ncrypt_pgp_functions.html", null ],
    [ "Wrapper around calls to external PGP program", "ncrypt_pgpinvoke.html", null ],
    [ "PGP key management routines", "ncrypt_pgpkey.html", null ],
    [ "Misc PGP helper routines", "ncrypt_pgplib.html", null ],
    [ "Identify the hash algorithm from a PGP signature", "ncrypt_pgpmicalg.html", null ],
    [ "Parse PGP data packets", "ncrypt_pgppacket.html", null ],
    [ "SMIME helper routines", "ncrypt_smime.html", null ],
    [ "Smime functions", "ncrypt_smime_functions.html", null ],
    [ "GPGME Key Sorting", "ncrypt_sort_gpgme.html", null ],
    [ "PGP Key Sorting", "ncrypt_sort_pgp.html", null ]
];