var lib_mutt =
[
    [ "Linear array API", "mutt_array.html", null ],
    [ "Parse a number in a string", "mutt_atoi.html", null ],
    [ "Conversion to/from base64 encoding", "mutt_base64.html", null ],
    [ "Helper object for storing and parsing strings", "mutt_buffer.html", null ],
    [ "Conversion between different character encodings", "mutt_charset.html", null ],
    [ "ctype(3) wrapper functions", "mutt_ctype.html", null ],
    [ "Time and date handling routines", "mutt_date.html", null ],
    [ "Private copy of the environment variables", "mutt_envlist.html", null ],
    [ "Case-insensitive fixed-chunk comparisons", "mutt_eqi.html", null ],
    [ "Leave the program NOW", "mutt_exit.html", null ],
    [ "File management functions", "mutt_file.html", null ],
    [ "Pass files through external commands (filters)", "mutt_filter.html", null ],
    [ "Hash Table data structure", "mutt_hash.html", null ],
    [ "Singly-linked list type", "mutt_list.html", null ],
    [ "Logging Dispatcher", "mutt_logging.html", null ],
    [ "Map between a string and a constant", "mutt_mapping.html", null ],
    [ "Multi-byte String manipulation functions", "mutt_mbyte.html", null ],
    [ "Calculate the MD5 checksum of a buffer", "mutt_md5.html", null ],
    [ "Memory management wrappers", "mutt_memory.html", null ],
    [ "Definition of the Mutt Module", "mutt_module.html", null ],
    [ "Notification API", "mutt_notify.html", null ],
    [ "Path manipulation functions", "mutt_path.html", null ],
    [ "A global pool of Buffers", "mutt_pool.html", null ],
    [ "Manage precompiled / predefined regular expressions", "mutt_prex.html", null ],
    [ "Context-free sorting function", "mutt_qsort_r.html", null ],
    [ "Random number/string functions", "mutt_random.html", null ],
    [ "Manage regular expressions", "mutt_regex.html", null ],
    [ "Signal handling", "mutt_signal.html", null ],
    [ "A separated list of strings", "mutt_slist.html", null ],
    [ "Keep track when processing files", "mutt_state.html", null ],
    [ "String manipulation functions", "mutt_string.html", null ],
    [ "For systems lacking timegm()", "mutt_timegm.html", null ],
    [ "For systems lacking wcscasecmp()", "mutt_wcscasecmp.html", null ]
];