var searchData=
[
  ['pager_20function_20api_0',['Pager Function API',['../group__pager__function__api.html',1,'']]],
  ['parse_1',['parse()',['../group__command__parse.html',1,'']]],
  ['parse_20a_20pattern_20api_2',['Parse a pattern API',['../group__eat__arg__api.html',1,'']]],
  ['parse_20api_3',['Expando Parse API',['../group__expando__parse__api.html',1,'']]],
  ['parser_20api_4',['POP Response Parser API',['../group__pop__fetch__api.html',1,'']]],
  ['parsing_20api_5',['Colour Parsing API',['../group__parser__callback__api.html',1,'']]],
  ['path_5fcanon_6',['path_canon()',['../group__mx__path__canon.html',1,'']]],
  ['path_5fis_5fempty_7',['path_is_empty()',['../group__mx__path__is__empty.html',1,'']]],
  ['path_5fprobe_8',['path_probe()',['../group__mx__path__probe.html',1,'']]],
  ['pattern_20api_9',['Parse a pattern API',['../group__eat__arg__api.html',1,'']]],
  ['pattern_20function_20api_10',['Pattern Function API',['../group__pattern__function__api.html',1,'']]],
  ['pgp_20function_20api_11',['Pgp Function API',['../group__pgp__function__api.html',1,'']]],
  ['pgp_5fcheck_5ftraditional_12',['pgp_check_traditional()',['../group__crypto__pgp__check__traditional.html',1,'']]],
  ['pgp_5fencrypt_5fmessage_13',['pgp_encrypt_message()',['../group__crypto__pgp__encrypt__message.html',1,'']]],
  ['pgp_5fextract_5fkey_5ffrom_5fattachment_14',['pgp_extract_key_from_attachment()',['../group__crypto__pgp__extract__key__from__attachment.html',1,'']]],
  ['pgp_5finvoke_5fgetkeys_15',['pgp_invoke_getkeys()',['../group__crypto__pgp__invoke__getkeys.html',1,'']]],
  ['pgp_5finvoke_5fimport_16',['pgp_invoke_import()',['../group__crypto__pgp__invoke__import.html',1,'']]],
  ['pgp_5fmake_5fkey_5fattachment_17',['pgp_make_key_attachment()',['../group__crypto__pgp__make__key__attachment.html',1,'']]],
  ['pgp_5ftraditional_5fencryptsign_18',['pgp_traditional_encryptsign()',['../group__crypto__pgp__traditional__encryptsign.html',1,'']]],
  ['poll_19',['poll()',['../group__connection__poll.html',1,'']]],
  ['pop_20authentication_20api_20',['POP Authentication API',['../group__pop__authenticate.html',1,'']]],
  ['pop_20response_20parser_20api_21',['POP Response Parser API',['../group__pop__fetch__api.html',1,'']]],
  ['postpone_20function_20api_22',['Postpone Function API',['../group__postpone__function__api.html',1,'']]],
  ['predicate_20api_23',['Address Predicate API',['../group__addr__predicate__api.html',1,'']]],
  ['preview_20function_20api_24',['Preview Function API',['../group__preview__function__api.html',1,'']]],
  ['private_20data_20api_25',['Private Data API',['../group__account__adata__free.html',1,'Account Private Data API'],['../group__email__edata__free.html',1,'Email Private Data API'],['../group__mailbox__mdata__free.html',1,'Mailbox Private Data API']]]
];
