var searchData=
[
  ['mailbox_20api_0',['Mailbox API',['../group__mx__api.html',1,'']]],
  ['mailbox_20private_20data_20api_1',['Mailbox Private Data API',['../group__mailbox__mdata__free.html',1,'']]],
  ['mailing_20list_20function_20api_2',['Mailing-list Function API',['../group__mlist__function__api.html',1,'']]],
  ['make_5fentry_3',['make_entry()',['../group__menu__make__entry.html',1,'']]],
  ['mapping_20api_4',['File Mapping API',['../group__mutt__file__map__api.html',1,'']]],
  ['mbox_5fcheck_5',['mbox_check()',['../group__mx__mbox__check.html',1,'']]],
  ['mbox_5fcheck_5fstats_6',['mbox_check_stats()',['../group__mx__mbox__check__stats.html',1,'']]],
  ['mbox_5fclose_7',['mbox_close()',['../group__mx__mbox__close.html',1,'']]],
  ['mbox_5fopen_8',['mbox_open()',['../group__mx__mbox__open.html',1,'']]],
  ['mbox_5fopen_5fappend_9',['mbox_open_append()',['../group__mx__mbox__open__append.html',1,'']]],
  ['mbox_5fsync_10',['mbox_sync()',['../group__mx__mbox__sync.html',1,'']]],
  ['mdata_5ffree_11',['mdata_free()',['../group__menu__mdata__free.html',1,'']]],
  ['menu_20api_12',['Menu API',['../group__menu__api.html',1,'']]],
  ['menu_20function_20api_13',['Menu Function API',['../group__menu__function__api.html',1,'']]],
  ['message_20windows_14',['GUI: Message Windows',['../group__gui__mw.html',1,'']]],
  ['mime_20encoder_20api_15',['Mime Encoder API',['../group__encoder__api.html',1,'']]],
  ['mime_20handler_20api_16',['Mime Handler API',['../group__handler__api.html',1,'']]],
  ['module_20api_17',['Config Module API',['../group__cfg__module__api.html',1,'']]],
  ['msg_5fclose_18',['msg_close()',['../group__mx__msg__close.html',1,'']]],
  ['msg_5fcommit_19',['msg_commit()',['../group__mx__msg__commit.html',1,'']]],
  ['msg_5fopen_20',['msg_open()',['../group__mx__msg__open.html',1,'']]],
  ['msg_5fopen_5fnew_21',['msg_open_new()',['../group__mx__msg__open__new.html',1,'']]],
  ['msg_5fpadding_5fsize_22',['msg_padding_size()',['../group__mx__msg__padding__size.html',1,'']]],
  ['msg_5fsave_5fhcache_23',['msg_save_hcache()',['../group__mx__msg__save__hcache.html',1,'']]]
];
