var searchData=
[
  ['s_20header_0',['Manipulate an email&apos;s header',['../neo_mutt_header.html',1,'index']]],
  ['s_20position_20selection_1',['Change the Menu&apos;s position/selection',['../menu_move.html',1,'lib_menu']]],
  ['sasl_20authentication_2',['SASL authentication',['../imap_auth_gsasl.html',1,'GNU SASL authentication'],['../conn_sasl.html',1,'SASL authentication'],['../imap_auth_sasl.html',1,'SASL authentication']]],
  ['sasl_20authentication_20support_3',['GNU SASL authentication support',['../conn_gsasl.html',1,'lib_conn']]],
  ['sasl_20plain_20authentication_4',['SASL plain authentication',['../conn_sasl_plain.html',1,'lib_conn']]],
  ['schema_5',['Autocrypt database schema',['../autocrypt_schema.html',1,'lib_autocrypt']]],
  ['schemes_6',['Parse URL schemes',['../email_url.html',1,'lib_email']]],
  ['scores_20to_20emails_7',['Routines for adding user scores to emails',['../neo_score.html',1,'index']]],
  ['screen_8',['GUI handle the resizing of the screen',['../gui_resize.html',1,'lib_gui']]],
  ['scripting_9',['Integrated Lua scripting',['../neo_mutt_lua.html',1,'index']]],
  ['search_10',['Holds state of a search',['../pattern_search_state.html',1,'lib_pattern']]],
  ['search_20routines_11',['Search routines',['../imap_search.html',1,'lib_imap']]],
  ['selectable_20list_12',['GUI present the user with a selectable list',['../menu_menu.html',1,'lib_menu']]],
  ['selection_13',['Change the Menu&apos;s position/selection',['../menu_move.html',1,'lib_menu']]],
  ['selection_20dialog_14',['Selection Dialog',['../attach_dlg_attach.html',1,'Attachment Selection Dialog'],['../crypt_dlg_gpgme.html',1,'GPGME Key Selection Dialog'],['../history_dlg_history.html',1,'History Selection Dialog'],['../pattern_dlg_pattern.html',1,'Pattern Selection Dialog'],['../crypt_dlg_pgp.html',1,'PGP Key Selection Dialog'],['../postpone_dlg_postpone.html',1,'Postponed Email Selection Dialog'],['../crypt_dlg_smime.html',1,'SMIME Key Selection Dialog']]],
  ['send_15',['Send',['../lib_send.html',1,'']]],
  ['send_20an_20email_16',['Prepare and send an email',['../send_send.html',1,'lib_send']]],
  ['send_20email_20to_20an_20smtp_20server_17',['Send email to an SMTP server',['../send_smtp.html',1,'lib_send']]],
  ['send_20email_20using_20sendmail_18',['Send email using sendmail',['../send_sendmail.html',1,'lib_send']]],
  ['send_20receive_20commands_19',['Send/receive commands',['../imap_command.html',1,'lib_imap']]],
  ['send_20reply_20with_20an_20attachment_20',['Send/reply with an attachment',['../neo_recvcmd.html',1,'index']]],
  ['sending_20an_20email_21',['Miscellaneous functions for sending an email',['../send_sendlib.html',1,'lib_send']]],
  ['sendmail_22',['Send email using sendmail',['../send_sendmail.html',1,'lib_send']]],
  ['separated_20list_20of_20strings_23',['A separated list of strings',['../mutt_slist.html',1,'lib_mutt']]],
  ['sequences_24',['Sequences',['../mh_sequence.html',1,'MH Mailbox Sequences'],['../color_parse_ansi.html',1,'Parse ANSI Sequences']]],
  ['serialiser_25',['Email-object serialiser',['../hc_serial.html',1,'lib_hcache']]],
  ['server_26',['server',['../send_smtp.html',1,'Send email to an SMTP server'],['../nntp_nntp.html',1,'Talk to an NNTP server']]],
  ['set_27',['Config Set',['../config_set.html',1,'lib_config']]],
  ['set_20command_28',['Parse the &apos;set&apos; command',['../parse_set.html',1,'lib_parse']]],
  ['set_20the_20terminal_20title_20icon_29',['Set the terminal title/icon',['../gui_terminal.html',1,'lib_gui']]],
  ['set_20up_20the_20extended_20keys_30',['Set up the extended keys',['../key_extended.html',1,'lib_key']]],
  ['set_20up_20the_20key_20bindings_31',['Set up the key bindings',['../key_init.html',1,'lib_key']]],
  ['sets_32',['IMAP Message Sets',['../imap_msg_set.html',1,'lib_imap']]],
  ['shared_20attachments_20functions_33',['Shared attachments functions',['../attach_mutt_attach.html',1,'lib_attach']]],
  ['shared_20code_34',['Shared code',['../expando_helpers.html',1,'lib_expando']]],
  ['shared_20code_35',['Autocrypt shared code',['../autocrypt_autocrypt.html',1,'lib_autocrypt']]],
  ['shared_20code_20for_20alias_20dialogs_36',['Shared code for alias dialogs',['../alias_gui.html',1,'lib_alias']]],
  ['shared_20compression_20code_37',['Shared compression code',['../compress_compress.html',1,'lib_compress']]],
  ['shared_20data_38',['Compose Shared Data',['../compose_shared_data.html',1,'lib_compose']]],
  ['shared_20data_39',['Shared data',['../index_shared_data.html',1,'lib_index']]],
  ['shared_20debug_20code_40',['Shared debug code',['../debug_common.html',1,'lib_debug']]],
  ['shared_20functions_41',['shared functions',['../maildir_shared.html',1,'Maildir shared functions'],['../mh_shared.html',1,'MH shared functions']]],
  ['shared_20store_20code_42',['Shared store code',['../store_store.html',1,'lib_store']]],
  ['side_20panel_43',['GUI display the mailboxes in a side panel',['../sidebar_sidebar.html',1,'lib_sidebar']]],
  ['sidebar_44',['Sidebar',['../lib_sidebar.html',1,'']]],
  ['sidebar_20commands_45',['Sidebar commands',['../sidebar_commands.html',1,'lib_sidebar']]],
  ['sidebar_20expando_20definitions_46',['Sidebar Expando definitions',['../sidebar_expando.html',1,'lib_sidebar']]],
  ['sidebar_20functions_47',['Sidebar functions',['../sidebar_functions.html',1,'lib_sidebar']]],
  ['sidebar_20observers_48',['Sidebar observers',['../sidebar_observers.html',1,'lib_sidebar']]],
  ['sidebar_20sort_20functions_49',['Sidebar sort functions',['../sidebar_sort.html',1,'lib_sidebar']]],
  ['sidebar_20window_50',['Sidebar Window',['../sidebar_window.html',1,'lib_sidebar']]],
  ['sidebar_20window_20data_51',['Sidebar Window data',['../sidebar_wdata.html',1,'lib_sidebar']]],
  ['sign_20encrypt_20check_20routines_52',['PGP sign, encrypt, check routines',['../crypt_pgp.html',1,'lib_ncrypt']]],
  ['signal_20handling_53',['Signal handling',['../mutt_signal.html',1,'Signal handling'],['../neo_mutt_signal.html',1,'Signal handling']]],
  ['signature_54',['Identify the hash algorithm from a PGP signature',['../crypt_pgpmicalg.html',1,'lib_ncrypt']]],
  ['signing_20encryption_20multiplexor_55',['Signing/encryption multiplexor',['../crypt_crypt.html',1,'lib_ncrypt']]],
  ['simple_20bar_20status_56',['Simple Bar (status)',['../gui_sbar.html',1,'lib_gui']]],
  ['simple_20colour_57',['Simple colour',['../color_simple.html',1,'lib_color']]],
  ['simple_20dialog_58',['Simple Dialog',['../gui_simple.html',1,'lib_gui']]],
  ['simple_20pager_20dialog_59',['Simple Pager Dialog',['../pager_dopager.html',1,'lib_pager']]],
  ['simple_20string_20formatting_60',['Simple string formatting',['../expando_format.html',1,'lib_expando']]],
  ['singly_20linked_20list_20type_61',['Singly-linked list type',['../mutt_list.html',1,'lib_mutt']]],
  ['smime_62',['SMIME',['../crypt_crypt_mod_smime.html',1,'Wrappers for calls to CLI SMIME'],['../crypt_crypt_mod_smime_gpgme.html',1,'Wrappers for calls to GPGME SMIME']]],
  ['smime_20calls_20to_20gpgme_63',['Wrapper for PGP/SMIME calls to GPGME',['../crypt_crypt_gpgme.html',1,'lib_ncrypt']]],
  ['smime_20functions_64',['Smime functions',['../crypt_functions.html',1,'PGP/Smime functions'],['../smime_functions.html',1,'Smime functions']]],
  ['smime_20helper_20routines_65',['SMIME helper routines',['../crypt_smime.html',1,'lib_ncrypt']]],
  ['smime_20key_20selection_20dialog_66',['SMIME Key Selection Dialog',['../crypt_dlg_smime.html',1,'lib_ncrypt']]],
  ['smtp_20server_67',['Send email to an SMTP server',['../send_smtp.html',1,'lib_send']]],
  ['socket_20code_68',['Low-level socket code',['../conn_raw.html',1,'lib_conn']]],
  ['socket_20handling_69',['Low-level socket handling',['../conn_socket.html',1,'lib_conn']]],
  ['some_20miscellaneous_20functions_70',['Some miscellaneous functions',['../neo_muttlib.html',1,'index']]],
  ['sort_20functions_71',['Sidebar sort functions',['../sidebar_sort.html',1,'lib_sidebar']]],
  ['sorting_72',['Sorting',['../crypt_sort_gpgme.html',1,'GPGME Key Sorting'],['../crypt_sort_pgp.html',1,'PGP Key Sorting'],['../config_sort.html',1,'Type: Sorting']]],
  ['sorting_73',['sorting',['../alias_sort.html',1,'Alias sorting'],['../browser_sorting.html',1,'Browser sorting']]],
  ['sorting_20function_74',['Context-free sorting function',['../mutt_qsort_r.html',1,'lib_mutt']]],
  ['sorting_20methods_75',['Email sorting methods',['../email_sort.html',1,'lib_email']]],
  ['specific_20account_20data_76',['specific Account data',['../nntp_adata.html',1,'Nntp-specific Account data'],['../nm_adata.html',1,'Notmuch-specific Account data'],['../pop_adata.html',1,'Pop-specific Account data']]],
  ['specific_20email_20data_77',['specific Email data',['../imap_edata.html',1,'Imap-specific Email data'],['../maildir_edata.html',1,'Maildir-specific Email data'],['../nntp_edata.html',1,'Nntp-specific Email data'],['../nm_edata.html',1,'Notmuch-specific Email data'],['../pop_edata.html',1,'Pop-specific Email data']]],
  ['specific_20mailbox_20data_78',['specific Mailbox data',['../imap_mdata.html',1,'Imap-specific Mailbox data'],['../maildir_mdata.html',1,'Maildir-specific Mailbox data'],['../mh_mdata.html',1,'Mh-specific Mailbox data'],['../nntp_mdata.html',1,'Nntp-specific Mailbox data'],['../nm_mdata.html',1,'Notmuch-specific Mailbox data']]],
  ['state_20data_20for_20attachments_79',['Private state data for Attachments',['../attach_private_data.html',1,'lib_attach']]],
  ['state_20data_20for_20the_20pager_80',['Private state data for the Pager',['../pager_private_data.html',1,'lib_pager']]],
  ['state_20of_20a_20search_81',['Holds state of a search',['../pattern_search_state.html',1,'lib_pattern']]],
  ['state_20of_20text_20entry_82',['State of text entry',['../editor_state.html',1,'lib_editor']]],
  ['status_83',['status',['../compose_cbar.html',1,'Compose Bar (status)'],['../index_ibar.html',1,'Index Bar (status)'],['../gui_sbar.html',1,'Simple Bar (status)']]],
  ['status_20line_84',['status line',['../index_expando_status.html',1,'GUI display a user-configurable status line'],['../index_status.html',1,'GUI display a user-configurable status line']]],
  ['store_85',['Store',['../lib_store.html',1,'']]],
  ['store_20code_86',['Shared store code',['../store_store.html',1,'lib_store']]],
  ['storing_20and_20parsing_20strings_87',['Helper object for storing and parsing strings',['../mutt_buffer.html',1,'lib_mutt']]],
  ['string_88',['Type: String',['../config_string.html',1,'lib_config']]],
  ['string_89',['string',['../lib_editor.html',1,'Edit a string'],['../editor_window.html',1,'GUI ask the user to enter a string'],['../mutt_atoi.html',1,'Parse a number in a string'],['../lib_expando.html',1,'Parse Expando string']]],
  ['string_20and_20a_20constant_90',['Map between a string and a constant',['../mutt_mapping.html',1,'lib_mutt']]],
  ['string_20auto_20completion_20data_91',['String auto-completion data',['../complete_data.html',1,'lib_complete']]],
  ['string_20auto_20completion_20routines_92',['String auto-completion routines',['../complete_complete.html',1,'lib_complete']]],
  ['string_20formatting_93',['Simple string formatting',['../expando_format.html',1,'lib_expando']]],
  ['string_20functions_94',['Random number/string functions',['../mutt_random.html',1,'lib_mutt']]],
  ['string_20manipulation_20functions_95',['String manipulation functions',['../mutt_mbyte.html',1,'Multi-byte String manipulation functions'],['../mutt_string.html',1,'String manipulation functions']]],
  ['string_20processing_20routines_20to_20generate_20the_20mail_20index_96',['String processing routines to generate the mail index',['../index_expando_index.html',1,'lib_index']]],
  ['strings_97',['strings',['../mutt_slist.html',1,'A separated list of strings'],['../mutt_buffer.html',1,'Helper object for storing and parsing strings'],['../config_slist.html',1,'Type: List of strings']]],
  ['structure_98',['Hash Table data structure',['../mutt_hash.html',1,'lib_mutt']]],
  ['structure_20of_20an_20entire_20email_99',['Duplicate the structure of an entire email',['../neo_copy.html',1,'index']]],
  ['style_100',['Quoted style',['../color_qstyle.html',1,'lib_color']]],
  ['subject_20regex_20handling_101',['Subject Regex handling',['../neo_subjrx.html',1,'index']]],
  ['subscribed_20newsgroups_102',['Read/write a file of subscribed newsgroups',['../nntp_newsrc.html',1,'lib_nntp']]],
  ['subset_20of_20config_20items_103',['Subset of config items',['../config_subset.html',1,'lib_config']]],
  ['support_104',['support',['../conn_gsasl.html',1,'GNU SASL authentication support'],['../menu_tagging.html',1,'Tagging support']]],
  ['systems_20lacking_20timegm_105',['For systems lacking timegm()',['../neo_timegm.html',1,'index']]],
  ['systems_20lacking_20wcscasecmp_106',['For systems lacking wcscasecmp()',['../neo_wcscasecmp.html',1,'index']]]
];
