var searchData=
[
  ['cache_0',['Cache',['../lib_bcache.html',1,'Body (Message) Cache'],['../hcache_config.html',1,'Config used by Header Cache'],['../lib_hcache.html',1,'Email Header Cache'],['../maildir_hcache.html',1,'Maildir Header Cache']]],
  ['cache_20functions_1',['Body Cache functions',['../bcache_bcache.html',1,'lib_bcache']]],
  ['cache_20multiplexor_2',['Header cache multiplexor',['../hcache_hcache.html',1,'lib_hcache']]],
  ['cache_20of_20config_20variables_3',['Cache of config variables',['../core_config_cache.html',1,'lib_core']]],
  ['calculate_20the_20md5_20checksum_20of_20a_20buffer_4',['Calculate the MD5 checksum of a buffer',['../mutt_md5.html',1,'lib_mutt']]],
  ['callable_20functions_5',['All user-callable functions',['../gui_opcode.html',1,'lib_gui']]],
  ['calls_20to_20cli_20pgp_6',['Wrappers for calls to CLI PGP',['../ncrypt_crypt_mod_pgp.html',1,'lib_ncrypt']]],
  ['calls_20to_20cli_20smime_7',['Wrappers for calls to CLI SMIME',['../ncrypt_crypt_mod_smime.html',1,'lib_ncrypt']]],
  ['calls_20to_20external_20pgp_20program_8',['Wrapper around calls to external PGP program',['../ncrypt_pgpinvoke.html',1,'lib_ncrypt']]],
  ['calls_20to_20gpgme_9',['Wrapper for PGP/SMIME calls to GPGME',['../ncrypt_crypt_gpgme.html',1,'lib_ncrypt']]],
  ['calls_20to_20gpgme_20pgp_10',['Wrappers for calls to GPGME PGP',['../ncrypt_crypt_mod_pgp_gpgme.html',1,'lib_ncrypt']]],
  ['calls_20to_20gpgme_20smime_11',['Wrappers for calls to GPGME SMIME',['../ncrypt_crypt_mod_smime_gpgme.html',1,'lib_ncrypt']]],
  ['case_20insensitive_20fixed_20chunk_20comparisons_12',['Case-insensitive fixed-chunk comparisons',['../mutt_eqi.html',1,'lib_mutt']]],
  ['case_20matching_13',['Smart Case Matching',['../fuzzy_subseq.html#autotoc_md59',1,'']]],
  ['cases_14',['Use Cases',['../lib_fuzzy.html#autotoc_md50',1,'']]],
  ['certificate_20verification_20dialog_15',['Certificate Verification Dialog',['../conn_dlg_verifycert.html',1,'lib_conn']]],
  ['change_20the_20menu_20s_20position_20selection_16',['Change the Menu&apos;s position/selection',['../menu_move.html',1,'lib_menu']]],
  ['changes_17',['Monitor files for changes',['../main_monitor.html',1,'index']]],
  ['character_20encodings_18',['Conversion between different character encodings',['../mutt_charset.html',1,'lib_mutt']]],
  ['character_20table_19',['Type: Multi-byte character table',['../config_mbtable.html',1,'lib_config']]],
  ['characteristics_20',['Performance Characteristics',['../fuzzy_subseq.html#autotoc_md60',1,'']]],
  ['charset_21',['Validate charset',['../config_charset.html',1,'lib_config']]],
  ['charset_20conversion_22',['Charset Conversion',['../convert_convert.html',1,'File Charset Conversion'],['../lib_convert.html',1,'File Charset Conversion']]],
  ['charset_20functions_23',['RFC2231 MIME Charset functions',['../email_rfc2231.html',1,'lib_email']]],
  ['check_20routines_24',['PGP sign, encrypt, check routines',['../ncrypt_pgp.html',1,'lib_ncrypt']]],
  ['checksum_20of_20a_20buffer_25',['Calculate the MD5 checksum of a buffer',['../mutt_md5.html',1,'lib_mutt']]],
  ['chunk_20comparisons_26',['Case-insensitive fixed-chunk comparisons',['../mutt_eqi.html',1,'lib_mutt']]],
  ['cli_20pgp_27',['Wrappers for calls to CLI PGP',['../ncrypt_crypt_mod_pgp.html',1,'lib_ncrypt']]],
  ['cli_20pgp_20program_28',['Parse the output of CLI PGP program',['../ncrypt_gnupg.html',1,'lib_ncrypt']]],
  ['cli_20smime_29',['Wrappers for calls to CLI SMIME',['../ncrypt_crypt_mod_smime.html',1,'lib_ncrypt']]],
  ['client_30',['NeoMutt Email Client',['../lib_main.html',1,'index']]],
  ['code_31',['Debug Code',['../lib_debug.html',1,'']]],
  ['code_32',['code',['../autocrypt_autocrypt.html',1,'Autocrypt shared code'],['../lib_email.html',1,'Email code'],['../email_parse.html',1,'Email parsing code'],['../lib_gui.html',1,'Graphical code'],['../conn_raw.html',1,'Low-level socket code'],['../expando_helpers.html',1,'Shared code'],['../compress_compress.html',1,'Shared compression code'],['../debug_common.html',1,'Shared debug code'],['../store_store.html',1,'Shared store code'],['../gui_curs_lib.html',1,'Window drawing code']]],
  ['code_20backtrace_33',['Code backtrace',['../debug_backtrace.html',1,'lib_debug']]],
  ['code_20docs_34',['Code Docs',['../index.html',1,'']]],
  ['code_20for_20alias_20dialogs_35',['Shared code for alias dialogs',['../alias_gui.html',1,'lib_alias']]],
  ['codes_36',['Xterm Color Codes',['../attr_8c.html#autotoc_md21',1,'']]],
  ['color_37',['Color',['../lib_color.html',1,'Color'],['../color_config.html',1,'Config used by Color']]],
  ['color_20and_20attribute_20parsing_38',['Color and attribute parsing',['../color_color.html',1,'lib_color']]],
  ['color_20codes_39',['Xterm Color Codes',['../attr_8c.html#autotoc_md21',1,'']]],
  ['color_20module_40',['Definition of the Color Module',['../color_module.html',1,'lib_color']]],
  ['color_20palette_41',['Color palette',['../attr_8c.html#autotoc_md23',1,'']]],
  ['colors_42',['Basic and Bright Colors',['../attr_8c.html#autotoc_md22',1,'']]],
  ['colour_43',['Colour',['../color_curses.html',1,'Curses Colour'],['../color_regex.html',1,'Regex Colour']]],
  ['colour_44',['Simple colour',['../color_simple.html',1,'lib_color']]],
  ['colour_20and_20attributes_45',['Colour and attributes',['../color_attr.html',1,'lib_color']]],
  ['colour_20commands_46',['colour commands',['../color_commands.html',1,'Parse colour commands'],['../color_parse_color.html',1,'Parse colour commands']]],
  ['colour_20debugging_47',['Colour Debugging',['../color_debug.html',1,'lib_color']]],
  ['colour_20dump_20command_48',['Colour Dump Command',['../color_dump.html',1,'lib_color']]],
  ['colour_20notifications_49',['Colour notifications',['../color_notify.html',1,'lib_color']]],
  ['colours_50',['ANSI Colours',['../color_ansi.html',1,'lib_color']]],
  ['colours_51',['colours',['../color_merge.html',1,'Merged colours'],['../color_quote.html',1,'Quoted-Email colours']]],
  ['command_52',['Command',['../color_dump.html',1,'Colour Dump Command'],['../conn_account_ext_cmd.html',1,'Connection Credentials External Command']]],
  ['command_53',['Parse the &apos;set&apos; command',['../parse_set.html',1,'lib_parse']]],
  ['command_20line_54',['Command Line',['../lib_cli.html',1,'Parse the Command Line'],['../cli_parse.html',1,'Parse the Command Line']]],
  ['commands_55',['Commands',['../hooks_commands.html',1,'Hook Commands'],['../lib_hooks.html',1,'Hook Commands'],['../lua_commands.html',1,'Lua Commands'],['../lib_commands.html',1,'NeoMutt Commands'],['../core_command.html',1,'NeoMutt Commands'],['../alias_alternates.html',1,'Parse Alternate Commands'],['../alias_group.html',1,'Parse Group/Lists Commands'],['../commands_ifdef.html',1,'Parse Ifdef Commands'],['../email_ignore.html',1,'Parse Ignore Commands'],['../commands_mailboxes.html',1,'Parse Mailboxes Commands'],['../send_my_header.html',1,'Parse My-header Commands'],['../commands_setenv.html',1,'Parse Setenv Commands'],['../commands_parse.html',1,'Parse Simple Commands'],['../commands_source.html',1,'Parse Source Commands'],['../email_spam.html',1,'Parse Spam Commands'],['../commands_stailq.html',1,'Parse Stailq Commands'],['../index_subjectrx.html',1,'Parse subject-regex Commands'],['../send_commands.html',1,'Send Commands'],['../commands_commands.html',1,'Setup NeoMutt Commands']]],
  ['commands_56',['commands',['../alias_commands.html',1,'Alias commands'],['../attach_commands.html',1,'Attachment commands'],['../email_commands.html',1,'Email commands'],['../index_commands.html',1,'Index commands'],['../main_external.html',1,'Manage where the email is piped to external commands'],['../color_commands.html',1,'Parse colour commands'],['../color_parse_color.html',1,'Parse colour commands'],['../key_commands.html',1,'Parse key binding commands'],['../imap_command.html',1,'Send/receive commands'],['../sidebar_commands.html',1,'Sidebar commands']]],
  ['commands_20filters_57',['Pass files through external commands (filters)',['../mutt_filter.html',1,'lib_mutt']]],
  ['commands_20in_20a_20config_20file_58',['Functions to parse commands in a config file',['../parse_dump.html',1,'lib_parse']]],
  ['commands_20module_59',['Definition of the Commands Module',['../commands_module.html',1,'lib_commands']]],
  ['comparisons_60',['Case-insensitive fixed-chunk comparisons',['../mutt_eqi.html',1,'lib_mutt']]],
  ['compile_20a_20pattern_61',['Compile a Pattern',['../pattern_compile.html',1,'lib_pattern']]],
  ['complete_20module_62',['Definition of the Complete Module',['../complete_module.html',1,'lib_complete']]],
  ['complete_20nntp_20newsgroups_63',['Auto-complete NNTP newsgroups',['../nntp_complete.html',1,'lib_nntp']]],
  ['completion_64',['Completion',['../alias_complete.html',1,'Alias Auto-Completion'],['../browser_complete.html',1,'Browser Auto-Completion'],['../notmuch_complete.html',1,'Notmuch Auto-Completion'],['../pattern_complete.html',1,'Pattern Auto-Completion']]],
  ['completion_65',['Auto-completion',['../lib_complete.html',1,'']]],
  ['completion_20data_66',['String auto-completion data',['../complete_data.html',1,'lib_complete']]],
  ['completion_20helpers_67',['Auto-completion helpers',['../complete_helpers.html',1,'lib_complete']]],
  ['completion_20routines_68',['String auto-completion routines',['../complete_complete.html',1,'lib_complete']]],
  ['compmbox_20module_69',['Definition of the Compmbox Module',['../compmbox_module.html',1,'lib_compmbox']]],
  ['compose_70',['Config used by Compose',['../compose_config.html',1,'lib_compose']]],
  ['compose_20an_20email_71',['Compose an Email',['../lib_compose.html',1,'']]],
  ['compose_20bar_20data_72',['Compose Bar Data',['../compose_cbar_data.html',1,'lib_compose']]],
  ['compose_20bar_20status_73',['Compose Bar (status)',['../compose_cbar.html',1,'lib_compose']]],
  ['compose_20email_20dialog_74',['Compose Email Dialog',['../compose_dlg_compose.html',1,'lib_compose']]],
  ['compose_20functions_75',['Compose functions',['../compose_functions.html',1,'lib_compose']]],
  ['compose_20module_76',['Definition of the Compose Module',['../compose_module.html',1,'lib_compose']]],
  ['compose_20shared_20data_77',['Compose Shared Data',['../compose_shared_data.html',1,'lib_compose']]],
  ['compress_20expando_20definitions_78',['Compress Expando definitions',['../compmbox_expando.html',1,'lib_compmbox']]],
  ['compress_20module_79',['Definition of the Compress Module',['../compress_module.html',1,'lib_compress']]],
  ['compressed_20mailbox_80',['Compressed Mailbox',['../lib_compmbox.html',1,'']]],
  ['compressed_20mailbox_20functions_81',['Compressed mailbox functions',['../compmbox_compress.html',1,'lib_compmbox']]],
  ['compression_82',['compression',['../compress_lz4.html',1,'LZ4 compression'],['../compress_zlib.html',1,'ZLIB compression'],['../compress_zstd.html',1,'Zstandard (zstd) compression']]],
  ['compression_20code_83',['Shared compression code',['../compress_compress.html',1,'lib_compress']]],
  ['compression_20functions_84',['Compression functions',['../lib_compress.html',1,'']]],
  ['compression_20of_20network_20traffic_85',['Zlib compression of network traffic',['../conn_zstrm.html',1,'lib_conn']]],
  ['condition_20boolean_20node_86',['Condition Boolean Node',['../expando_node_condbool.html',1,'lib_expando']]],
  ['condition_20node_87',['Condition Node',['../expando_node_condition.html',1,'lib_expando']]],
  ['conditional_20date_20node_88',['Conditional Date Node',['../expando_node_conddate.html',1,'lib_expando']]],
  ['config_89',['Config',['../alias_config.html',1,'Alias Config'],['../autocrypt_config.html',1,'Autocrypt Config'],['../lib_config.html',1,'Config']]],
  ['config_90',['Dump all the config',['../config_dump.html',1,'lib_config']]],
  ['config_20file_91',['config file',['../parse_dump.html',1,'Functions to parse commands in a config file'],['../parse_rc.html',1,'Parse lines from a config file']]],
  ['config_20items_92',['Subset of config items',['../config_subset.html',1,'lib_config']]],
  ['config_20module_93',['Definition of the Config Module',['../config_module.html',1,'lib_config']]],
  ['config_20set_94',['Config Set',['../config_set.html',1,'lib_config']]],
  ['config_20type_3a_20email_20address_95',['Config type: Email address',['../address_config_type.html',1,'lib_address']]],
  ['config_20used_20by_20color_96',['Config used by Color',['../color_config.html',1,'']]],
  ['config_20used_20by_20compose_97',['Config used by Compose',['../compose_config.html',1,'lib_compose']]],
  ['config_20used_20by_20header_20cache_98',['Config used by Header Cache',['../hcache_config.html',1,'lib_hcache']]],
  ['config_20used_20by_20help_20bar_99',['Config used by Help Bar',['../helpbar_config.html',1,'lib_helpbar']]],
  ['config_20used_20by_20imap_100',['Config used by IMAP',['../imap_config.html',1,'lib_imap']]],
  ['config_20used_20by_20libaddress_101',['Config used by libaddress',['../address_config.html',1,'lib_address']]],
  ['config_20used_20by_20libattach_102',['Config used by libattach',['../attach_config.html',1,'lib_attach']]],
  ['config_20used_20by_20libbrowser_103',['Config used by libbrowser',['../browser_config.html',1,'lib_browser']]],
  ['config_20used_20by_20libconn_104',['Config used by libconn',['../conn_config.html',1,'lib_conn']]],
  ['config_20used_20by_20libgui_105',['Config used by libgui',['../gui_config.html',1,'lib_gui']]],
  ['config_20used_20by_20libhooks_106',['Config used by libhooks',['../hooks_config.html',1,'lib_hooks']]],
  ['config_20used_20by_20libmbox_107',['Config used by libmbox',['../mbox_config.html',1,'lib_mbox']]],
  ['config_20used_20by_20libmenu_108',['Config used by libmenu',['../menu_config.html',1,'lib_menu']]],
  ['config_20used_20by_20libncrypt_109',['Config used by libncrypt',['../ncrypt_config.html',1,'lib_ncrypt']]],
  ['config_20used_20by_20libnntp_110',['Config used by libnntp',['../nntp_config.html',1,'lib_nntp']]],
  ['config_20used_20by_20libnotmuch_111',['Config used by libnotmuch',['../notmuch_config.html',1,'lib_notmuch']]],
  ['config_20used_20by_20libpager_112',['Config used by libpager',['../pager_config.html',1,'lib_pager']]],
  ['config_20used_20by_20libpattern_113',['Config used by libpattern',['../pattern_config.html',1,'lib_pattern']]],
  ['config_20used_20by_20libpop_114',['Config used by libpop',['../pop_config.html',1,'lib_pop']]],
  ['config_20used_20by_20libsend_115',['Config used by libsend',['../send_config.html',1,'lib_send']]],
  ['config_20used_20by_20libsidebar_116',['Config used by libsidebar',['../sidebar_config.html',1,'lib_sidebar']]],
  ['config_20used_20by_20maildir_117',['Config used by Maildir',['../maildir_config.html',1,'lib_maildir']]],
  ['config_20used_20by_20mh_118',['Config used by Mh',['../mh_config.html',1,'lib_mh']]],
  ['config_20used_20by_20the_20email_20library_119',['Config used by the Email library',['../email_config.html',1,'lib_email']]],
  ['config_20used_20by_20the_20history_120',['Config used by the history',['../history_config.html',1,'lib_history']]],
  ['config_20used_20by_20the_20index_121',['Config used by the Index',['../index_config.html',1,'lib_index']]],
  ['config_20used_20by_20the_20progress_20bar_122',['Config used by the Progress Bar',['../progress_config.html',1,'lib_progress']]],
  ['config_20values_123',['Helper functions to get config values',['../config_helpers.html',1,'lib_config']]],
  ['config_20variables_124',['config variables',['../core_config_cache.html',1,'Cache of config variables'],['../main_mutt_config.html',1,'Definitions of config variables']]],
  ['configurable_20status_20line_125',['configurable status line',['../index_expando_status.html',1,'GUI display a user-configurable status line'],['../index_status.html',1,'GUI display a user-configurable status line']]],
  ['conn_20module_126',['Definition of the Conn Module',['../conn_module.html',1,'lib_conn']]],
  ['connaccount_20object_20used_20by_20pop_20and_20imap_127',['ConnAccount object used by POP and IMAP',['../conn_mutt_account.html',1,'lib_conn']]],
  ['connection_20credentials_128',['Connection Credentials',['../conn_account.html',1,'lib_conn']]],
  ['connection_20credentials_20external_20command_129',['Connection Credentials External Command',['../conn_account_ext_cmd.html',1,'lib_conn']]],
  ['connections_130',['connections',['../main_mutt_socket.html',1,'NeoMutt connections'],['../lib_conn.html',1,'Network connections']]],
  ['constant_131',['Map between a string and a constant',['../mutt_mapping.html',1,'lib_mutt']]],
  ['container_132',['Container',['../gui_bottombar.html',1,'Bottom Bar Container'],['../gui_msgcont.html',1,'Message Container']]],
  ['container_20node_133',['Container Node',['../expando_node_container.html',1,'lib_expando']]],
  ['content_134',['Decide how to display email content',['../email_handler.html',1,'lib_email']]],
  ['content_20id_20header_20functions_135',['Attachment Content-ID header functions',['../attach_cid.html',1,'lib_attach']]],
  ['content_20info_20extraction_136',['Content Info Extraction',['../convert_content_info.html',1,'lib_convert']]],
  ['context_137',['Parse Context',['../parse_context.html',1,'lib_parse']]],
  ['context_20free_20sorting_20function_138',['Context-free sorting function',['../mutt_qsort_r.html',1,'lib_mutt']]],
  ['conversion_139',['Conversion',['../convert_convert.html',1,'File Charset Conversion'],['../lib_convert.html',1,'File Charset Conversion']]],
  ['conversion_20between_20different_20character_20encodings_140',['Conversion between different character encodings',['../mutt_charset.html',1,'lib_mutt']]],
  ['conversion_20to_20from_20base64_20encoding_141',['Conversion to/from base64 encoding',['../mutt_base64.html',1,'lib_mutt']]],
  ['convert_20module_142',['Definition of the Convert Module',['../convert_module.html',1,'lib_convert']]],
  ['copy_20of_20the_20environment_20variables_143',['Private copy of the environment variables',['../mutt_envlist.html',1,'lib_mutt']]],
  ['copy_20the_20body_20of_20an_20email_144',['Copy the body of an email',['../email_copy_body.html',1,'lib_email']]],
  ['copyright_20about_20neomutt_145',['Display version and copyright about NeoMutt',['../main_version.html',1,'index']]],
  ['core_20module_146',['Definition of the Core Module',['../core_module.html',1,'lib_core']]],
  ['core_20neomutt_20objects_147',['Core NeoMutt objects',['../lib_core.html',1,'']]],
  ['cram_20md5_20authentication_148',['CRAM-MD5 authentication',['../imap_auth_cram.html',1,'lib_imap']]],
  ['create_20manipulate_20threading_20in_20emails_149',['Create/manipulate threading in emails',['../gui_thread.html',1,'lib_gui']]],
  ['create_20temporary_20files_150',['Create Temporary Files',['../core_tmp.html',1,'lib_core']]],
  ['credentials_151',['Connection Credentials',['../conn_account.html',1,'lib_conn']]],
  ['credentials_20external_20command_152',['Connection Credentials External Command',['../conn_account_ext_cmd.html',1,'lib_conn']]],
  ['crypto_20functions_153',['Wrapper around crypto functions',['../ncrypt_cryptglue.html',1,'lib_ncrypt']]],
  ['crypto_20modules_154',['Register crypto modules',['../ncrypt_crypt_mod.html',1,'lib_ncrypt']]],
  ['ctype_203_20wrapper_20functions_155',['ctype(3) wrapper functions',['../mutt_ctype.html',1,'lib_mutt']]],
  ['curses_156',['Wrapper around Curses',['../gui_curses.html',1,'lib_gui']]],
  ['curses_20colour_157',['Curses Colour',['../color_curses.html',1,'lib_color']]]
];
