var searchData=
[
  ['gdbm_0',['GNU dbm (GDBM)',['../store_gdbm.html',1,'lib_store']]],
  ['generate_20the_20help_20page_20and_20gui_20display_20it_1',['Generate the help-page and GUI display it',['../neo_help.html',1,'index']]],
  ['generate_20the_20mail_20index_2',['String processing routines to generate the mail index',['../index_expando_index.html',1,'lib_index']]],
  ['get_20a_20key_20from_20the_20user_3',['Get a key from the user',['../key_get.html',1,'lib_key']]],
  ['get_20config_20values_4',['Helper functions to get config values',['../config_helpers.html',1,'lib_config']]],
  ['global_20functions_5',['Global functions',['../gui_global.html',1,'lib_gui']]],
  ['global_20pool_20of_20buffers_6',['A global pool of Buffers',['../mutt_pool.html',1,'lib_mutt']]],
  ['global_20variables_7',['Global Variables',['../email_globals.html',1,'lib_email']]],
  ['global_20variables_8',['Global variables',['../neo_globals.html',1,'index']]],
  ['gnu_20dbm_20gdbm_9',['GNU dbm (GDBM)',['../store_gdbm.html',1,'lib_store']]],
  ['gnu_20sasl_20authentication_10',['GNU SASL authentication',['../imap_auth_gsasl.html',1,'lib_imap']]],
  ['gnu_20sasl_20authentication_20support_11',['GNU SASL authentication support',['../conn_gsasl.html',1,'lib_conn']]],
  ['gnutls_20encryption_12',['GnuTLS encryption',['../conn_gnutls.html',1,'lib_conn']]],
  ['gpgme_13',['Wrapper for PGP/SMIME calls to GPGME',['../crypt_crypt_gpgme.html',1,'lib_ncrypt']]],
  ['gpgme_20functions_14',['Gpgme functions',['../crypt_gpgme_functions.html',1,'lib_ncrypt']]],
  ['gpgme_20handler_15',['Autocrypt GPGME handler',['../autocrypt_gpgme.html',1,'lib_autocrypt']]],
  ['gpgme_20key_20selection_20dialog_16',['GPGME Key Selection Dialog',['../crypt_dlg_gpgme.html',1,'lib_ncrypt']]],
  ['gpgme_20key_20sorting_17',['GPGME Key Sorting',['../crypt_sort_gpgme.html',1,'lib_ncrypt']]],
  ['gpgme_20pgp_18',['Wrappers for calls to GPGME PGP',['../crypt_crypt_mod_pgp_gpgme.html',1,'lib_ncrypt']]],
  ['gpgme_20smime_19',['Wrappers for calls to GPGME SMIME',['../crypt_crypt_mod_smime_gpgme.html',1,'lib_ncrypt']]],
  ['graphical_20code_20',['Graphical code',['../lib_gui.html',1,'']]],
  ['graphviz_20dot_20file_21',['GraphViz dot file',['../debug_graphviz.html',1,'lib_debug']]],
  ['greeting_20expando_20definitions_22',['Greeting Expando definitions',['../send_expando_greeting.html',1,'lib_send']]],
  ['groups_23',['groups',['../addr_group.html',1,'Address groups'],['../nntp_expando_browser.html',1,'Browse NNTP groups'],['../nntp_expando_newsrc.html',1,'Browse NNTP groups']]],
  ['gss_20authentication_24',['GSS authentication',['../imap_auth_gss.html',1,'lib_imap']]],
  ['gui_20ask_20the_20user_20to_20enter_20a_20string_25',['GUI ask the user to enter a string',['../editor_window.html',1,'lib_editor']]],
  ['gui_20display_20a_20user_20configurable_20status_20line_26',['GUI display a user configurable status line',['../index_expando_status.html',1,'GUI display a user-configurable status line'],['../index_status.html',1,'GUI display a user-configurable status line']]],
  ['gui_20display_20it_27',['Generate the help-page and GUI display it',['../neo_help.html',1,'index']]],
  ['gui_20display_20the_20mailboxes_20in_20a_20side_20panel_28',['GUI display the mailboxes in a side panel',['../sidebar_sidebar.html',1,'lib_sidebar']]],
  ['gui_20handle_20the_20resizing_20of_20the_20screen_29',['GUI handle the resizing of the screen',['../gui_resize.html',1,'lib_gui']]],
  ['gui_20present_20the_20user_20with_20a_20selectable_20list_30',['GUI present the user with a selectable list',['../menu_menu.html',1,'lib_menu']]]
];
