var searchData=
[
  ['s_20header_0',['Manipulate an email&apos;s header',['../email_header.html',1,'lib_email']]],
  ['s_20position_20selection_1',['Change the Menu&apos;s position/selection',['../menu_move.html',1,'lib_menu']]],
  ['sasl_20authentication_2',['SASL authentication',['../imap_auth_gsasl.html',1,'GNU SASL authentication'],['../conn_sasl.html',1,'SASL authentication'],['../imap_auth_sasl.html',1,'SASL authentication']]],
  ['sasl_20authentication_20support_3',['GNU SASL authentication support',['../conn_gsasl.html',1,'lib_conn']]],
  ['sasl_20plain_20authentication_4',['SASL plain authentication',['../conn_sasl_plain.html',1,'lib_conn']]],
  ['scale_20ramp_5',['Grey Scale Ramp',['../attr_8c.html#autotoc_md24',1,'']]],
  ['scenarios_6',['Test Scenarios',['../fuzzy_benchmark.html#autotoc_md46',1,'']]],
  ['schema_7',['Autocrypt database schema',['../autocrypt_schema.html',1,'lib_autocrypt']]],
  ['schema_20version_8',['Database schema version',['../lib_autocrypt.html#autotoc_md17',1,'']]],
  ['schemes_9',['Parse URL schemes',['../email_url.html',1,'lib_email']]],
  ['score_10',['Base Score',['../fuzzy_subseq.html#autotoc_md56',1,'']]],
  ['scores_20to_20emails_11',['Routines for adding user scores to emails',['../email_score.html',1,'lib_email']]],
  ['scoring_20rules_12',['Scoring Rules',['../fuzzy_subseq.html#autotoc_md55',1,'']]],
  ['screen_13',['GUI handle the resizing of the screen',['../gui_resize.html',1,'lib_gui']]],
  ['scripting_14',['scripting',['../lib_lua.html',1,'Integrated Lua scripting'],['../lua_lua.html',1,'Integrated Lua scripting']]],
  ['search_15',['Holds state of a search',['../pattern_search_state.html',1,'lib_pattern']]],
  ['search_20routines_16',['Search routines',['../imap_search.html',1,'lib_imap']]],
  ['sec_5fautocrypt_17',['&lt;span class=&quot;tt&quot;&gt;header-&amp;gt;security | SEC_AUTOCRYPT&lt;/span&gt;',['../lib_autocrypt.html#autotoc_md14',1,'']]],
  ['sec_5fautocrypt_5foverride_18',['&lt;span class=&quot;tt&quot;&gt;header-&amp;gt;security | SEC_AUTOCRYPT_OVERRIDE&lt;/span&gt;',['../lib_autocrypt.html#autotoc_md15',1,'']]],
  ['security_20sec_5fautocrypt_19',['&lt;span class=&quot;tt&quot;&gt;header-&amp;gt;security | SEC_AUTOCRYPT&lt;/span&gt;',['../lib_autocrypt.html#autotoc_md14',1,'']]],
  ['security_20sec_5fautocrypt_5foverride_20',['&lt;span class=&quot;tt&quot;&gt;header-&amp;gt;security | SEC_AUTOCRYPT_OVERRIDE&lt;/span&gt;',['../lib_autocrypt.html#autotoc_md15',1,'']]],
  ['selectable_20list_21',['GUI present the user with a selectable list',['../menu_menu.html',1,'lib_menu']]],
  ['selection_22',['Change the Menu&apos;s position/selection',['../menu_move.html',1,'lib_menu']]],
  ['selection_20dialog_23',['Selection Dialog',['../attach_dlg_attach.html',1,'Attachment Selection Dialog'],['../ncrypt_dlg_gpgme.html',1,'GPGME Key Selection Dialog'],['../history_dlg_history.html',1,'History Selection Dialog'],['../pattern_dlg_pattern.html',1,'Pattern Selection Dialog'],['../ncrypt_dlg_pgp.html',1,'PGP Key Selection Dialog'],['../postpone_dlg_postpone.html',1,'Postponed Email Selection Dialog'],['../ncrypt_dlg_smime.html',1,'SMIME Key Selection Dialog']]],
  ['selection_20of_20attachments_20for_20an_20action_24',['Build a selection of Attachments for an action',['../attach_selection.html',1,'lib_attach']]],
  ['selection_20of_20emails_20for_20an_20action_25',['Build a selection of Emails for an action',['../gui_selection.html',1,'lib_gui']]],
  ['send_26',['Send',['../lib_send.html',1,'']]],
  ['send_20an_20email_27',['Prepare and send an email',['../send_send.html',1,'lib_send']]],
  ['send_20commands_28',['Send Commands',['../send_commands.html',1,'']]],
  ['send_20email_20to_20an_20smtp_20server_29',['Send email to an SMTP server',['../send_smtp.html',1,'lib_send']]],
  ['send_20email_20using_20sendmail_30',['Send email using sendmail',['../send_sendmail.html',1,'lib_send']]],
  ['send_20module_31',['Definition of the Send Module',['../send_module.html',1,'lib_send']]],
  ['send_20receive_20commands_32',['Send/receive commands',['../imap_command.html',1,'lib_imap']]],
  ['send_20reply_20with_20an_20attachment_33',['Send/reply with an attachment',['../attach_recvcmd.html',1,'lib_attach']]],
  ['sending_20an_20email_34',['Miscellaneous functions for sending an email',['../send_sendlib.html',1,'lib_send']]],
  ['sendmail_35',['Send email using sendmail',['../send_sendmail.html',1,'lib_send']]],
  ['separated_20list_20of_20strings_36',['A separated list of strings',['../mutt_slist.html',1,'lib_mutt']]],
  ['sequences_37',['Sequences',['../mh_sequence.html',1,'MH Mailbox Sequences'],['../color_parse_ansi.html',1,'Parse ANSI Sequences']]],
  ['serialiser_38',['Email-object serialiser',['../hcache_serial.html',1,'lib_hcache']]],
  ['server_39',['server',['../send_smtp.html',1,'Send email to an SMTP server'],['../nntp_nntp.html',1,'Talk to an NNTP server']]],
  ['set_40',['Config Set',['../config_set.html',1,'lib_config']]],
  ['set_20command_41',['Parse the &apos;set&apos; command',['../parse_set.html',1,'lib_parse']]],
  ['set_20the_20terminal_20title_20icon_42',['Set the terminal title/icon',['../gui_terminal.html',1,'lib_gui']]],
  ['set_20up_20the_20extended_20keys_43',['Set up the extended keys',['../key_extended.html',1,'lib_key']]],
  ['set_20up_20the_20key_20bindings_44',['Set up the key bindings',['../key_init.html',1,'lib_key']]],
  ['setenv_20commands_45',['Parse Setenv Commands',['../commands_setenv.html',1,'lib_commands']]],
  ['sets_46',['IMAP Message Sets',['../imap_msg_set.html',1,'lib_imap']]],
  ['setup_20neomutt_20commands_47',['Setup NeoMutt Commands',['../commands_commands.html',1,'lib_commands']]],
  ['shared_20attachments_20functions_48',['Shared attachments functions',['../attach_mutt_attach.html',1,'lib_attach']]],
  ['shared_20code_49',['Shared code',['../expando_helpers.html',1,'lib_expando']]],
  ['shared_20code_50',['Autocrypt shared code',['../autocrypt_autocrypt.html',1,'lib_autocrypt']]],
  ['shared_20code_20for_20alias_20dialogs_51',['Shared code for alias dialogs',['../alias_gui.html',1,'lib_alias']]],
  ['shared_20compression_20code_52',['Shared compression code',['../compress_compress.html',1,'lib_compress']]],
  ['shared_20data_53',['Compose Shared Data',['../compose_shared_data.html',1,'lib_compose']]],
  ['shared_20data_54',['Shared data',['../index_shared_data.html',1,'lib_index']]],
  ['shared_20debug_20code_55',['Shared debug code',['../debug_common.html',1,'lib_debug']]],
  ['shared_20functions_56',['shared functions',['../maildir_shared.html',1,'Maildir shared functions'],['../mh_shared.html',1,'MH shared functions']]],
  ['shared_20store_20code_57',['Shared store code',['../store_store.html',1,'lib_store']]],
  ['side_20panel_58',['GUI display the mailboxes in a side panel',['../sidebar_sidebar.html',1,'lib_sidebar']]],
  ['sidebar_59',['Sidebar',['../lib_sidebar.html',1,'']]],
  ['sidebar_20commands_60',['Sidebar commands',['../sidebar_commands.html',1,'lib_sidebar']]],
  ['sidebar_20expando_20definitions_61',['Sidebar Expando definitions',['../sidebar_expando.html',1,'lib_sidebar']]],
  ['sidebar_20functions_62',['Sidebar functions',['../sidebar_functions_sidebar.html',1,'lib_sidebar']]],
  ['sidebar_20module_63',['Definition of the Sidebar Module',['../sidebar_module.html',1,'lib_sidebar']]],
  ['sidebar_20observers_64',['Sidebar observers',['../sidebar_observers.html',1,'lib_sidebar']]],
  ['sidebar_20sort_20functions_65',['Sidebar sort functions',['../sidebar_sort.html',1,'lib_sidebar']]],
  ['sidebar_20window_66',['Sidebar Window',['../sidebar_window.html',1,'lib_sidebar']]],
  ['sidebar_20window_20data_67',['Sidebar Window data',['../sidebar_wdata.html',1,'lib_sidebar']]],
  ['sign_20encrypt_20check_20routines_68',['PGP sign, encrypt, check routines',['../ncrypt_pgp.html',1,'lib_ncrypt']]],
  ['signal_20handling_69',['Signal handling',['../mutt_signal.html',1,'Signal handling'],['../main_mutt_signal.html',1,'Signal handling']]],
  ['signature_70',['Identify the hash algorithm from a PGP signature',['../ncrypt_pgpmicalg.html',1,'lib_ncrypt']]],
  ['signing_20encryption_20multiplexor_71',['Signing/encryption multiplexor',['../ncrypt_crypt.html',1,'lib_ncrypt']]],
  ['simple_20bar_20status_72',['Simple Bar (status)',['../gui_sbar.html',1,'lib_gui']]],
  ['simple_20colour_73',['Simple colour',['../color_simple.html',1,'lib_color']]],
  ['simple_20commands_74',['Parse Simple Commands',['../commands_parse.html',1,'lib_commands']]],
  ['simple_20dialog_75',['Simple Dialog',['../gui_simple.html',1,'lib_gui']]],
  ['simple_20pager_20dialog_76',['Simple Pager Dialog',['../pager_dopager.html',1,'lib_pager']]],
  ['simple_20string_20formatting_77',['Simple string formatting',['../expando_format.html',1,'lib_expando']]],
  ['singly_20linked_20list_20type_78',['Singly-linked list type',['../mutt_list.html',1,'lib_mutt']]],
  ['smart_20case_20matching_79',['Smart Case Matching',['../fuzzy_subseq.html#autotoc_md59',1,'']]],
  ['smime_80',['SMIME',['../ncrypt_crypt_mod_smime.html',1,'Wrappers for calls to CLI SMIME'],['../ncrypt_crypt_mod_smime_gpgme.html',1,'Wrappers for calls to GPGME SMIME']]],
  ['smime_20calls_20to_20gpgme_81',['Wrapper for PGP/SMIME calls to GPGME',['../ncrypt_crypt_gpgme.html',1,'lib_ncrypt']]],
  ['smime_20functions_82',['Smime functions',['../ncrypt_functions.html',1,'PGP/Smime functions'],['../ncrypt_smime_functions.html',1,'Smime functions']]],
  ['smime_20helper_20routines_83',['SMIME helper routines',['../ncrypt_smime.html',1,'lib_ncrypt']]],
  ['smime_20key_20selection_20dialog_84',['SMIME Key Selection Dialog',['../ncrypt_dlg_smime.html',1,'lib_ncrypt']]],
  ['smtp_20server_85',['Send email to an SMTP server',['../send_smtp.html',1,'lib_send']]],
  ['socket_20code_86',['Low-level socket code',['../conn_raw.html',1,'lib_conn']]],
  ['socket_20handling_87',['Low-level socket handling',['../conn_socket.html',1,'lib_conn']]],
  ['some_20miscellaneous_20functions_88',['Some miscellaneous functions',['../main_muttlib.html',1,'index']]],
  ['sort_20functions_89',['Sidebar sort functions',['../sidebar_sort.html',1,'lib_sidebar']]],
  ['sorting_90',['Sorting',['../ncrypt_sort_gpgme.html',1,'GPGME Key Sorting'],['../ncrypt_sort_pgp.html',1,'PGP Key Sorting'],['../config_sort.html',1,'Type: Sorting']]],
  ['sorting_91',['sorting',['../alias_sort.html',1,'Alias sorting'],['../browser_sorting.html',1,'Browser sorting']]],
  ['sorting_20function_92',['Context-free sorting function',['../mutt_qsort_r.html',1,'lib_mutt']]],
  ['sorting_20methods_93',['Email sorting methods',['../email_sort.html',1,'lib_email']]],
  ['source_94',['Source',['../lib_compress.html#autotoc_md38',1,'Source'],['../lib_hcache.html#autotoc_md88',1,'Source'],['../lib_store.html#autotoc_md150',1,'Source']]],
  ['source_20commands_95',['Parse Source Commands',['../commands_source.html',1,'lib_commands']]],
  ['spam_20commands_96',['Parse Spam Commands',['../email_spam.html',1,'lib_email']]],
  ['specific_20account_20data_97',['specific Account data',['../nntp_adata.html',1,'Nntp-specific Account data'],['../notmuch_adata.html',1,'Notmuch-specific Account data'],['../pop_adata.html',1,'Pop-specific Account data']]],
  ['specific_20email_20data_98',['specific Email data',['../imap_edata.html',1,'Imap-specific Email data'],['../maildir_edata.html',1,'Maildir-specific Email data'],['../nntp_edata.html',1,'Nntp-specific Email data'],['../notmuch_edata.html',1,'Notmuch-specific Email data'],['../pop_edata.html',1,'Pop-specific Email data']]],
  ['specific_20mailbox_20data_99',['specific Mailbox data',['../imap_mdata.html',1,'Imap-specific Mailbox data'],['../maildir_mdata.html',1,'Maildir-specific Mailbox data'],['../mh_mdata.html',1,'Mh-specific Mailbox data'],['../nntp_mdata.html',1,'Nntp-specific Mailbox data'],['../notmuch_mdata.html',1,'Notmuch-specific Mailbox data']]],
  ['stailq_20commands_100',['Parse Stailq Commands',['../commands_stailq.html',1,'lib_commands']]],
  ['state_20data_20for_20attachments_101',['Private state data for Attachments',['../attach_private_data.html',1,'lib_attach']]],
  ['state_20data_20for_20the_20pager_102',['Private state data for the Pager',['../pager_private_data.html',1,'lib_pager']]],
  ['state_20of_20a_20search_103',['Holds state of a search',['../pattern_search_state.html',1,'lib_pattern']]],
  ['state_20of_20text_20entry_104',['State of text entry',['../editor_state.html',1,'lib_editor']]],
  ['status_105',['status',['../compose_cbar.html',1,'Compose Bar (status)'],['../index_ibar.html',1,'Index Bar (status)'],['../gui_sbar.html',1,'Simple Bar (status)']]],
  ['status_20line_106',['status line',['../index_expando_status.html',1,'GUI display a user-configurable status line'],['../index_status.html',1,'GUI display a user-configurable status line']]],
  ['still_20todo_107',['Still Todo',['../lib_autocrypt.html#autotoc_md12',1,'']]],
  ['store_108',['Store',['../lib_store.html',1,'']]],
  ['store_20code_109',['Shared store code',['../store_store.html',1,'lib_store']]],
  ['store_20module_110',['Definition of the Store Module',['../store_module.html',1,'lib_store']]],
  ['storing_20and_20parsing_20strings_111',['Helper object for storing and parsing strings',['../mutt_buffer.html',1,'lib_mutt']]],
  ['string_112',['Type: String',['../config_string.html',1,'lib_config']]],
  ['string_113',['string',['../lib_editor.html',1,'Edit a string'],['../editor_window.html',1,'GUI ask the user to enter a string'],['../mutt_atoi.html',1,'Parse a number in a string'],['../lib_expando.html',1,'Parse Expando string']]],
  ['string_20and_20a_20constant_114',['Map between a string and a constant',['../mutt_mapping.html',1,'lib_mutt']]],
  ['string_20auto_20completion_20data_115',['String auto-completion data',['../complete_data.html',1,'lib_complete']]],
  ['string_20auto_20completion_20routines_116',['String auto-completion routines',['../complete_complete.html',1,'lib_complete']]],
  ['string_20formatting_117',['Simple string formatting',['../expando_format.html',1,'lib_expando']]],
  ['string_20functions_118',['Random number/string functions',['../mutt_random.html',1,'lib_mutt']]],
  ['string_20manipulation_20functions_119',['String manipulation functions',['../mutt_mbyte.html',1,'Multi-byte String manipulation functions'],['../mutt_string.html',1,'String manipulation functions']]],
  ['string_20processing_20routines_20to_20generate_20the_20mail_20index_120',['String processing routines to generate the mail index',['../index_expando_index.html',1,'lib_index']]],
  ['strings_121',['strings',['../mutt_slist.html',1,'A separated list of strings'],['../mutt_buffer.html',1,'Helper object for storing and parsing strings'],['../config_slist.html',1,'Type: List of strings']]],
  ['structure_122',['Hash Table data structure',['../mutt_hash.html',1,'lib_mutt']]],
  ['structure_20of_20an_20entire_20email_123',['Duplicate the structure of an entire email',['../email_copy_email.html',1,'lib_email']]],
  ['style_124',['Quoted style',['../color_qstyle.html',1,'lib_color']]],
  ['subject_20regex_20commands_125',['Parse subject-regex Commands',['../index_subjectrx.html',1,'lib_index']]],
  ['submenus_126',['Maniplate Menus and SubMenus',['../key_menu.html',1,'lib_key']]],
  ['subscribed_20newsgroups_127',['Read/write a file of subscribed newsgroups',['../nntp_newsrc.html',1,'lib_nntp']]],
  ['subsequence_20fuzzy_20matching_128',['Subsequence fuzzy matching',['../fuzzy_subseq.html',1,'lib_fuzzy']]],
  ['subset_20of_20config_20items_129',['Subset of config items',['../config_subset.html',1,'lib_config']]],
  ['support_130',['UTF-8 Support',['../fuzzy_subseq.html#autotoc_md54',1,'']]],
  ['support_131',['support',['../conn_gsasl.html',1,'GNU SASL authentication support'],['../menu_tagging.html',1,'Tagging support']]],
  ['systems_20lacking_20timegm_132',['For systems lacking timegm()',['../mutt_timegm.html',1,'lib_mutt']]],
  ['systems_20lacking_20wcscasecmp_133',['For systems lacking wcscasecmp()',['../mutt_wcscasecmp.html',1,'lib_mutt']]]
];
