var searchData=
[
  ['mail_20index_0',['String processing routines to generate the mail index',['../index_expando_index.html',1,'lib_index']]],
  ['mailbox_1',['Mailbox',['../lib_compmbox.html',1,'Compressed Mailbox'],['../lib_imap.html',1,'Imap Mailbox'],['../lib_maildir.html',1,'Maildir Mailbox'],['../maildir_mailbox.html',1,'Maildir Mailbox'],['../lib_mh.html',1,'Mh Mailbox'],['../gui_mview.html',1,'View of a Mailbox']]],
  ['mailbox_2',['mailbox',['../imap_imap.html',1,'IMAP network mailbox'],['../pop_pop.html',1,'POP network mailbox']]],
  ['mailbox_20browser_3',['Mailbox Browser',['../lib_browser.html',1,'']]],
  ['mailbox_20browser_4',['Mailbox browser',['../imap_browse.html',1,'lib_imap']]],
  ['mailbox_20browser_20dialog_5',['File/Mailbox Browser Dialog',['../browser_dlg_browser.html',1,'lib_browser']]],
  ['mailbox_20data_6',['Mailbox data',['../imap_mdata.html',1,'Imap-specific Mailbox data'],['../maildir_mdata.html',1,'Maildir-specific Mailbox data'],['../mh_mdata.html',1,'Mh-specific Mailbox data'],['../nntp_mdata.html',1,'Nntp-specific Mailbox data'],['../notmuch_mdata.html',1,'Notmuch-specific Mailbox data']]],
  ['mailbox_20functions_7',['Compressed mailbox functions',['../compmbox_compress.html',1,'lib_compmbox']]],
  ['mailbox_20helper_20functions_8',['Mailbox helper functions',['../main_mutt_mailbox.html',1,'index']]],
  ['mailbox_20multiplexor_9',['Mailbox multiplexor',['../main_mx.html',1,'index']]],
  ['mailbox_20object_10',['Mailbox object',['../core_mailbox.html',1,'lib_core']]],
  ['mailbox_20sequences_11',['MH Mailbox Sequences',['../mh_sequence.html',1,'lib_mh']]],
  ['mailbox_20type_12',['mailbox type',['../maildir_maildir.html',1,'Maildir local mailbox type'],['../mbox_mbox.html',1,'Mbox local mailbox type'],['../mh_mh.html',1,'MH local mailbox type'],['../notmuch_notmuch.html',1,'Notmuch virtual mailbox type']]],
  ['mailboxes_20commands_13',['Parse Mailboxes Commands',['../commands_mailboxes.html',1,'lib_commands']]],
  ['mailboxes_20in_20a_20side_20panel_14',['GUI display the mailboxes in a side panel',['../sidebar_sidebar.html',1,'lib_sidebar']]],
  ['mailcap_20routines_15',['RFC1524 Mailcap routines',['../email_mailcap.html',1,'lib_email']]],
  ['maildir_16',['Config used by Maildir',['../maildir_config.html',1,'lib_maildir']]],
  ['maildir_20account_17',['Maildir Account',['../maildir_account.html',1,'lib_maildir']]],
  ['maildir_20email_20helper_18',['Maildir Email helper',['../maildir_mdemail.html',1,'lib_maildir']]],
  ['maildir_20header_20cache_19',['Maildir Header Cache',['../maildir_hcache.html',1,'lib_maildir']]],
  ['maildir_20local_20mailbox_20type_20',['Maildir local mailbox type',['../maildir_maildir.html',1,'lib_maildir']]],
  ['maildir_20mailbox_21',['Maildir Mailbox',['../lib_maildir.html',1,'Maildir Mailbox'],['../maildir_mailbox.html',1,'Maildir Mailbox']]],
  ['maildir_20message_22',['Maildir Message',['../maildir_message.html',1,'lib_maildir']]],
  ['maildir_20module_23',['Definition of the Maildir Module',['../maildir_module.html',1,'lib_maildir']]],
  ['maildir_20path_20handling_24',['Maildir Path handling',['../maildir_path.html',1,'lib_maildir']]],
  ['maildir_20shared_20functions_25',['Maildir shared functions',['../maildir_shared.html',1,'lib_maildir']]],
  ['maildir_20specific_20email_20data_26',['Maildir-specific Email data',['../maildir_edata.html',1,'lib_maildir']]],
  ['maildir_20specific_20mailbox_20data_27',['Maildir-specific Mailbox data',['../maildir_mdata.html',1,'lib_maildir']]],
  ['mailing_20lists_28',['Handle mailing lists',['../address_maillist.html',1,'lib_address']]],
  ['main_20module_29',['Definition of the Main Module',['../main_module.html',1,'index']]],
  ['manage_20precompiled_20predefined_20regular_20expressions_30',['Manage precompiled / predefined regular expressions',['../mutt_prex.html',1,'lib_mutt']]],
  ['manage_20regular_20expressions_31',['Manage regular expressions',['../mutt_regex.html',1,'lib_mutt']]],
  ['manage_20where_20the_20email_20is_20piped_20to_20external_20commands_32',['Manage where the email is piped to external commands',['../main_external.html',1,'index']]],
  ['management_33',['Window management',['../gui_window.html',1,'lib_gui']]],
  ['management_20functions_34',['File management functions',['../mutt_file.html',1,'lib_mutt']]],
  ['management_20routines_35',['PGP key management routines',['../ncrypt_pgpkey.html',1,'lib_ncrypt']]],
  ['management_20wrappers_36',['Memory management wrappers',['../mutt_memory.html',1,'lib_mutt']]],
  ['manager_20qdbm_37',['Quick Database Manager (QDBM)',['../store_qdbm.html',1,'lib_store']]],
  ['maniplate_20menus_20and_20submenus_38',['Maniplate Menus and SubMenus',['../key_menu.html',1,'lib_key']]],
  ['manipulate_20an_20email_20s_20header_39',['Manipulate an email&apos;s header',['../email_header.html',1,'lib_email']]],
  ['manipulate_20multipart_20emails_40',['Manipulate multipart Emails',['../send_multipart.html',1,'lib_send']]],
  ['manipulate_20the_20flags_20in_20an_20email_20header_41',['Manipulate the flags in an email header',['../main_flags.html',1,'index']]],
  ['manipulate_20threading_20in_20emails_42',['Create/manipulate threading in emails',['../gui_thread.html',1,'lib_gui']]],
  ['manipulation_43',['UTF-7 Manipulation',['../imap_utf7.html',1,'lib_imap']]],
  ['manipulation_20functions_44',['manipulation functions',['../mutt_mbyte.html',1,'Multi-byte String manipulation functions'],['../mutt_path.html',1,'Path manipulation functions'],['../mutt_string.html',1,'String manipulation functions']]],
  ['map_20between_20a_20string_20and_20a_20constant_45',['Map between a string and a constant',['../mutt_mapping.html',1,'lib_mutt']]],
  ['mapped_20database_20lmdb_46',['Lightning Memory-Mapped Database (LMDB)',['../store_lmdb.html',1,'lib_store']]],
  ['mappings_47',['Key mappings',['../lib_key.html',1,'']]],
  ['match_20patterns_20to_20emails_48',['Match patterns to emails',['../pattern_pattern.html',1,'lib_pattern']]],
  ['mbox_49',['Mbox',['../lib_mbox.html',1,'']]],
  ['mbox_20local_20mailbox_20type_50',['Mbox local mailbox type',['../mbox_mbox.html',1,'lib_mbox']]],
  ['mbox_20module_51',['Definition of the Mbox Module',['../mbox_module.html',1,'lib_mbox']]],
  ['md5_20authentication_52',['CRAM-MD5 authentication',['../imap_auth_cram.html',1,'lib_imap']]],
  ['md5_20checksum_20of_20a_20buffer_53',['Calculate the MD5 checksum of a buffer',['../mutt_md5.html',1,'lib_mutt']]],
  ['memory_20management_20wrappers_54',['Memory management wrappers',['../mutt_memory.html',1,'lib_mutt']]],
  ['memory_20mapped_20database_20lmdb_55',['Lightning Memory-Mapped Database (LMDB)',['../store_lmdb.html',1,'lib_store']]],
  ['menu_56',['Menu',['../lib_menu.html',1,'Menu'],['../menu_draw.html',1,'Paint the Menu'],['../menu_window.html',1,'Window wrapper around a Menu']]],
  ['menu_20functions_57',['Menu functions',['../menu_functions.html',1,'lib_menu']]],
  ['menu_20module_58',['Definition of the Menu Module',['../menu_module.html',1,'lib_menu']]],
  ['menu_20notification_20observers_59',['Menu notification observers',['../menu_observer.html',1,'lib_menu']]],
  ['menu_20s_20position_20selection_60',['Change the Menu&apos;s position/selection',['../menu_move.html',1,'lib_menu']]],
  ['menus_20and_20submenus_61',['Maniplate Menus and SubMenus',['../key_menu.html',1,'lib_key']]],
  ['merged_20colours_62',['Merged colours',['../color_merge.html',1,'lib_color']]],
  ['message_63',['Maildir Message',['../maildir_message.html',1,'lib_maildir']]],
  ['message_20cache_64',['Body (Message) Cache',['../lib_bcache.html',1,'']]],
  ['message_20container_65',['Message Container',['../gui_msgcont.html',1,'lib_gui']]],
  ['message_20for_20display_20in_20the_20pager_66',['Process a message for display in the pager',['../pager_message.html',1,'lib_pager']]],
  ['message_20id_20expando_20definitions_67',['Message Id Expando definitions',['../send_expando_msgid.html',1,'lib_send']]],
  ['message_20preview_20window_68',['Message Preview Window',['../compose_preview.html',1,'lib_compose']]],
  ['message_20sets_69',['IMAP Message Sets',['../imap_msg_set.html',1,'lib_imap']]],
  ['message_20window_70',['Message Window',['../gui_msgwin.html',1,'lib_gui']]],
  ['message_20window_20private_20data_71',['Message Window private data',['../gui_msgwin_wdata.html',1,'lib_gui']]],
  ['messages_72',['messages',['../imap_message.html',1,'IMAP messages'],['../pattern_message.html',1,'Pattern handling for messages']]],
  ['methods_73',['Email sorting methods',['../email_sort.html',1,'lib_email']]],
  ['mh_74',['Config used by Mh',['../mh_config.html',1,'lib_mh']]],
  ['mh_20email_20helper_75',['Mh Email helper',['../mh_mdemail.html',1,'lib_mh']]],
  ['mh_20local_20mailbox_20type_76',['MH local mailbox type',['../mh_mh.html',1,'lib_mh']]],
  ['mh_20mailbox_77',['Mh Mailbox',['../lib_mh.html',1,'']]],
  ['mh_20mailbox_20sequences_78',['MH Mailbox Sequences',['../mh_sequence.html',1,'lib_mh']]],
  ['mh_20module_79',['Definition of the Mh Module',['../mh_module.html',1,'lib_mh']]],
  ['mh_20shared_20functions_80',['MH shared functions',['../mh_shared.html',1,'lib_mh']]],
  ['mh_20specific_20mailbox_20data_81',['Mh-specific Mailbox data',['../mh_mdata.html',1,'lib_mh']]],
  ['mime_20charset_20functions_82',['RFC2231 MIME Charset functions',['../email_rfc2231.html',1,'lib_email']]],
  ['mime_20email_20header_20to_20a_20file_83',['Write a MIME Email Header to a file',['../send_header.html',1,'lib_send']]],
  ['mime_20email_20to_20a_20file_84',['Write a MIME Email to a file',['../send_body.html',1,'lib_send']]],
  ['mime_20encoding_85',['Data for MIME encoding',['../email_mime.html',1,'lib_email']]],
  ['mime_20part_86',['Attributes for a MIME part',['../email_parameter.html',1,'lib_email']]],
  ['misc_20pgp_20helper_20routines_87',['Misc PGP helper routines',['../ncrypt_pgplib.html',1,'lib_ncrypt']]],
  ['miscellaneous_20functions_88',['Some miscellaneous functions',['../main_muttlib.html',1,'index']]],
  ['miscellaneous_20functions_20for_20sending_20an_20email_89',['Miscellaneous functions for sending an email',['../send_sendlib.html',1,'lib_send']]],
  ['module_90',['Module',['../address_module.html',1,'Definition of the Address Module'],['../alias_module.html',1,'Definition of the Alias Module'],['../attach_module.html',1,'Definition of the Attach Module'],['../autocrypt_module.html',1,'Definition of the Autocrypt Module'],['../bcache_module.html',1,'Definition of the Bcache Module'],['../browser_module.html',1,'Definition of the Browser Module'],['../color_module.html',1,'Definition of the Color Module'],['../commands_module.html',1,'Definition of the Commands Module'],['../complete_module.html',1,'Definition of the Complete Module'],['../compmbox_module.html',1,'Definition of the Compmbox Module'],['../compose_module.html',1,'Definition of the Compose Module'],['../compress_module.html',1,'Definition of the Compress Module'],['../config_module.html',1,'Definition of the Config Module'],['../conn_module.html',1,'Definition of the Conn Module'],['../convert_module.html',1,'Definition of the Convert Module'],['../core_module.html',1,'Definition of the Core Module'],['../editor_module.html',1,'Definition of the Editor Module'],['../email_module.html',1,'Definition of the Email Module'],['../envelope_module.html',1,'Definition of the Envelope Module'],['../expando_module.html',1,'Definition of the Expando Module'],['../gui_module.html',1,'Definition of the Gui Module'],['../hcache_module.html',1,'Definition of the Hcache Module'],['../helpbar_module.html',1,'Definition of the Helpbar Module'],['../history_module.html',1,'Definition of the History Module'],['../hooks_module.html',1,'Definition of the Hooks Module'],['../imap_module.html',1,'Definition of the Imap Module'],['../index_module.html',1,'Definition of the Index Module'],['../key_module.html',1,'Definition of the Key Module'],['../lua_module.html',1,'Definition of the Lua Module'],['../maildir_module.html',1,'Definition of the Maildir Module'],['../main_module.html',1,'Definition of the Main Module'],['../mbox_module.html',1,'Definition of the Mbox Module'],['../menu_module.html',1,'Definition of the Menu Module'],['../mh_module.html',1,'Definition of the Mh Module'],['../mutt_module.html',1,'Definition of the Mutt Module'],['../ncrypt_module.html',1,'Definition of the Ncrypt Module'],['../nntp_module.html',1,'Definition of the Nntp Module'],['../notmuch_module.html',1,'Definition of the Notmuch Module'],['../pager_module.html',1,'Definition of the Pager Module'],['../parse_module.html',1,'Definition of the Parse Module'],['../pattern_module.html',1,'Definition of the Pattern Module'],['../pop_module.html',1,'Definition of the Pop Module'],['../postpone_module.html',1,'Definition of the Postpone Module'],['../progress_module.html',1,'Definition of the Progress Module'],['../question_module.html',1,'Definition of the Question Module'],['../send_module.html',1,'Definition of the Send Module'],['../sidebar_module.html',1,'Definition of the Sidebar Module'],['../store_module.html',1,'Definition of the Store Module']]],
  ['module_20api_91',['Module API',['../core_module_api.html',1,'lib_core']]],
  ['modules_92',['Register crypto modules',['../ncrypt_crypt_mod.html',1,'lib_ncrypt']]],
  ['monitor_20files_20for_20changes_93',['Monitor files for changes',['../main_monitor.html',1,'index']]],
  ['msn_20helper_20functions_94',['MSN helper functions',['../imap_msn.html',1,'lib_imap']]],
  ['multi_20byte_20character_20table_95',['Type: Multi-byte character table',['../config_mbtable.html',1,'lib_config']]],
  ['multi_20byte_20string_20manipulation_20functions_96',['Multi-byte String manipulation functions',['../mutt_mbyte.html',1,'lib_mutt']]],
  ['multipart_20emails_97',['Manipulate multipart Emails',['../send_multipart.html',1,'lib_send']]],
  ['multiplexor_98',['multiplexor',['../imap_auth.html',1,'Authenticator multiplexor'],['../hcache_hcache.html',1,'Header cache multiplexor'],['../main_mx.html',1,'Mailbox multiplexor'],['../ncrypt_crypt.html',1,'Signing/encryption multiplexor']]],
  ['mutt_99',['Mutt',['../lib_mutt.html',1,'']]],
  ['mutt_20module_100',['Definition of the Mutt Module',['../mutt_module.html',1,'lib_mutt']]],
  ['my_20header_20commands_101',['Parse My-header Commands',['../send_my_header.html',1,'lib_send']]],
  ['myvar_102',['Type: MyVar',['../config_myvar.html',1,'lib_config']]]
];
