var searchData=
[
  ['mailbox_20browser_0',['Mailbox browser',['../imap_browse.html',1,'lib_imap']]],
  ['mailbox_20browser_1',['Mailbox Browser',['../lib_browser.html',1,'']]],
  ['mailbox_20helper_20functions_2',['Mailbox helper functions',['../neo_mutt_mailbox.html',1,'index']]],
  ['mailbox_20multiplexor_3',['Mailbox multiplexor',['../neo_mx.html',1,'index']]],
  ['mailbox_20object_4',['Mailbox object',['../core_mailbox.html',1,'lib_core']]],
  ['maildir_20account_5',['Maildir Account',['../maildir_account.html',1,'lib_maildir']]],
  ['maildir_20email_20helper_6',['Maildir Email helper',['../maildir_mdemail.html',1,'lib_maildir']]],
  ['maildir_20header_20cache_7',['Maildir Header Cache',['../maildir_hcache.html',1,'lib_maildir']]],
  ['maildir_20local_20mailbox_20type_8',['Maildir local mailbox type',['../maildir_maildir.html',1,'lib_maildir']]],
  ['maildir_20mailbox_9',['Maildir Mailbox',['../lib_maildir.html',1,'(Global Namespace)'],['../maildir_mailbox.html',1,'lib_maildir']]],
  ['maildir_20message_10',['Maildir Message',['../maildir_message.html',1,'lib_maildir']]],
  ['maildir_20path_20handling_11',['Maildir Path handling',['../maildir_path.html',1,'lib_maildir']]],
  ['maildir_20shared_20functions_12',['Maildir shared functions',['../maildir_shared.html',1,'lib_maildir']]],
  ['maildir_2dspecific_20email_20data_13',['Maildir-specific Email data',['../maildir_edata.html',1,'lib_maildir']]],
  ['maildir_2dspecific_20mailbox_20data_14',['Maildir-specific Mailbox data',['../maildir_mdata.html',1,'lib_maildir']]],
  ['manage_20precompiled_20_2f_20predefined_20regular_20expressions_15',['Manage precompiled / predefined regular expressions',['../mutt_prex.html',1,'lib_mutt']]],
  ['manage_20regular_20expressions_16',['Manage regular expressions',['../mutt_regex.html',1,'lib_mutt']]],
  ['manage_20where_20the_20email_20is_20piped_20to_20external_20commands_17',['Manage where the email is piped to external commands',['../neo_external.html',1,'index']]],
  ['manipulate_20an_20email_27s_20header_18',['Manipulate an email&apos;s header',['../neo_mutt_header.html',1,'index']]],
  ['manipulate_20multipart_20emails_19',['Manipulate multipart Emails',['../send_multipart.html',1,'lib_send']]],
  ['manipulate_20the_20flags_20in_20an_20email_20header_20',['Manipulate the flags in an email header',['../neo_flags.html',1,'index']]],
  ['map_20between_20a_20string_20and_20a_20constant_21',['Map between a string and a constant',['../mutt_mapping.html',1,'lib_mutt']]],
  ['match_20patterns_20to_20emails_22',['Match patterns to emails',['../pattern_pattern.html',1,'lib_pattern']]],
  ['mbox_23',['Mbox',['../lib_mbox.html',1,'']]],
  ['mbox_20local_20mailbox_20type_24',['Mbox local mailbox type',['../mbox_mbox.html',1,'lib_mbox']]],
  ['memory_20management_20wrappers_25',['Memory management wrappers',['../mutt_memory.html',1,'lib_mutt']]],
  ['menu_26',['Menu',['../lib_menu.html',1,'']]],
  ['menu_20functions_27',['Menu functions',['../menu_functions.html',1,'lib_menu']]],
  ['menu_20notification_20observers_28',['Menu notification observers',['../menu_observer.html',1,'lib_menu']]],
  ['menu_20types_29',['Menu types',['../menu_type.html',1,'lib_menu']]],
  ['merged_20colours_30',['Merged colours',['../color_merge.html',1,'lib_color']]],
  ['message_20container_31',['Message Container',['../gui_msgcont.html',1,'lib_gui']]],
  ['message_20preview_20window_32',['Message Preview Window',['../compose_preview.html',1,'lib_compose']]],
  ['message_20window_33',['Message Window',['../gui_msgwin.html',1,'lib_gui']]],
  ['message_20window_20private_20data_34',['Message Window private data',['../gui_msgwin_wdata.html',1,'lib_gui']]],
  ['mh_20email_20helper_35',['Mh Email helper',['../mh_mdemail.html',1,'lib_mh']]],
  ['mh_20local_20mailbox_20type_36',['MH local mailbox type',['../mh_mh.html',1,'lib_mh']]],
  ['mh_20mailbox_37',['Mh Mailbox',['../lib_mh.html',1,'']]],
  ['mh_20mailbox_20sequences_38',['MH Mailbox Sequences',['../mh_sequence.html',1,'lib_mh']]],
  ['mh_20shared_20functions_39',['MH shared functions',['../mh_shared.html',1,'lib_mh']]],
  ['mh_2dspecific_20mailbox_20data_40',['Mh-specific Mailbox data',['../mh_mdata.html',1,'lib_mh']]],
  ['misc_20pgp_20helper_20routines_41',['Misc PGP helper routines',['../crypt_pgplib.html',1,'lib_ncrypt']]],
  ['miscellaneous_20functions_20for_20sending_20an_20email_42',['Miscellaneous functions for sending an email',['../send_sendlib.html',1,'lib_send']]],
  ['monitor_20files_20for_20changes_43',['Monitor files for changes',['../neo_monitor.html',1,'index']]],
  ['msn_20helper_20functions_44',['MSN helper functions',['../imap_msn.html',1,'lib_imap']]],
  ['multi_2dbyte_20string_20manipulation_20functions_45',['Multi-byte String manipulation functions',['../mutt_mbyte.html',1,'lib_mutt']]],
  ['mutt_46',['Mutt',['../lib_mutt.html',1,'']]]
];
