var searchData=
[
  ['data_0',['Data',['../compose_attach_data.html',1,'Attachment Data'],['../compose_cbar_data.html',1,'Compose Bar Data'],['../compose_shared_data.html',1,'Compose Shared Data'],['../envelope_wdata.html',1,'Envelope Window Data'],['../autocrypt_autocrypt_data.html',1,'Private Autocrypt Data'],['../pattern_pattern_data.html',1,'Private Pattern Data'],['../progress_wdata.html',1,'Progress Bar Window Data'],['../expando_render.html',1,'Render Expandos using Data']]],
  ['data_1',['data',['../imap_adata.html',1,'Account data'],['../imap_edata.html',1,'Imap-specific Email data'],['../imap_mdata.html',1,'Imap-specific Mailbox data'],['../maildir_edata.html',1,'Maildir-specific Email data'],['../maildir_mdata.html',1,'Maildir-specific Mailbox data'],['../gui_msgwin_wdata.html',1,'Message Window private data'],['../mh_mdata.html',1,'Mh-specific Mailbox data'],['../nntp_adata.html',1,'Nntp-specific Account data'],['../nntp_edata.html',1,'Nntp-specific Email data'],['../nntp_mdata.html',1,'Nntp-specific Mailbox data'],['../nm_adata.html',1,'Notmuch-specific Account data'],['../nm_edata.html',1,'Notmuch-specific Email data'],['../nm_mdata.html',1,'Notmuch-specific Mailbox data'],['../pop_adata.html',1,'Pop-specific Account data'],['../pop_edata.html',1,'Pop-specific Email data'],['../index_shared_data.html',1,'Shared data'],['../sidebar_wdata.html',1,'Sidebar Window data'],['../complete_data.html',1,'String auto-completion data']]],
  ['data_20for_20attachments_2',['Private state data for Attachments',['../attach_private_data.html',1,'lib_attach']]],
  ['data_20for_20mime_20encoding_3',['Data for MIME encoding',['../email_mime.html',1,'lib_email']]],
  ['data_20for_20the_20browser_4',['Private data for the Browser',['../browser_private_data.html',1,'lib_browser']]],
  ['data_20for_20the_20help_20bar_5',['Data for the Help Bar',['../helpbar_wdata.html',1,'lib_helpbar']]],
  ['data_20for_20the_20index_6',['Private data for the Index',['../index_private_data.html',1,'lib_index']]],
  ['data_20for_20the_20pager_7',['Private state data for the Pager',['../pager_private_data.html',1,'lib_pager']]],
  ['data_20packets_8',['Parse PGP data packets',['../crypt_pgppacket.html',1,'lib_ncrypt']]],
  ['data_20structure_9',['Hash Table data structure',['../mutt_hash.html',1,'lib_mutt']]],
  ['database_20handling_10',['database handling',['../autocrypt_db.html',1,'Autocrypt database handling'],['../nm_db.html',1,'Notmuch database handling']]],
  ['database_20lmdb_11',['Lightning Memory-Mapped Database (LMDB)',['../store_lmdb.html',1,'lib_store']]],
  ['database_20manager_20qdbm_12',['Quick Database Manager (QDBM)',['../store_qdbm.html',1,'lib_store']]],
  ['database_20schema_13',['Autocrypt database schema',['../autocrypt_schema.html',1,'lib_autocrypt']]],
  ['database_20tdb_14',['Trivial DataBase (TDB)',['../store_tdb.html',1,'lib_store']]],
  ['date_20handling_20routines_15',['Time and date handling routines',['../mutt_date.html',1,'lib_mutt']]],
  ['date_20node_16',['Conditional Date Node',['../expando_node_conddate.html',1,'lib_expando']]],
  ['db_20bdb_17',['Berkeley DB (BDB)',['../store_bdb.html',1,'lib_store']]],
  ['dbm_20gdbm_18',['GNU dbm (GDBM)',['../store_gdbm.html',1,'lib_store']]],
  ['debug_20code_19',['Debug Code',['../lib_debug.html',1,'']]],
  ['debug_20code_20',['Shared debug code',['../debug_common.html',1,'lib_debug']]],
  ['debug_20names_21',['Debug names',['../debug_names.html',1,'lib_debug']]],
  ['debugging_22',['Debugging',['../color_debug.html',1,'Colour Debugging'],['../debug_pager.html',1,'Pager Debugging']]],
  ['decide_20how_20to_20display_20email_20content_23',['Decide how to display email content',['../neo_handler.html',1,'index']]],
  ['decoding_24',['RFC2047 encoding / decoding',['../email_rfc2047.html',1,'lib_email']]],
  ['defined_20hooks_25',['defined Hooks',['../hooks_parse.html',1,'Parse user-defined Hooks'],['../hooks_run.html',1,'Run user-defined Hooks'],['../hooks_hook.html',1,'User-defined Hooks']]],
  ['definition_20of_20the_20address_20module_26',['Definition of the Address Module',['../addr_module.html',1,'lib_address']]],
  ['definition_20of_20the_20alias_20module_27',['Definition of the Alias Module',['../alias_module.html',1,'lib_alias']]],
  ['definition_20of_20the_20attach_20module_28',['Definition of the Attach Module',['../attach_module.html',1,'lib_attach']]],
  ['definition_20of_20the_20autocrypt_20module_29',['Definition of the Autocrypt Module',['../autocrypt_module.html',1,'lib_autocrypt']]],
  ['definition_20of_20the_20bcache_20module_30',['Definition of the Bcache Module',['../bcache_module.html',1,'lib_bcache']]],
  ['definition_20of_20the_20browser_20module_31',['Definition of the Browser Module',['../browser_module.html',1,'lib_browser']]],
  ['definition_20of_20the_20color_20module_32',['Definition of the Color Module',['../color_module.html',1,'lib_color']]],
  ['definition_20of_20the_20commands_20module_33',['Definition of the Commands Module',['../commands_module.html',1,'lib_command']]],
  ['definition_20of_20the_20complete_20module_34',['Definition of the Complete Module',['../complete_module.html',1,'lib_complete']]],
  ['definition_20of_20the_20compmbox_20module_35',['Definition of the Compmbox Module',['../compmbox_module.html',1,'lib_compmbox']]],
  ['definition_20of_20the_20compose_20module_36',['Definition of the Compose Module',['../compose_module.html',1,'lib_compose']]],
  ['definition_20of_20the_20compress_20module_37',['Definition of the Compress Module',['../compress_module.html',1,'lib_compress']]],
  ['definition_20of_20the_20config_20module_38',['Definition of the Config Module',['../config_module.html',1,'lib_config']]],
  ['definition_20of_20the_20conn_20module_39',['Definition of the Conn Module',['../conn_module.html',1,'lib_conn']]],
  ['definition_20of_20the_20convert_20module_40',['Definition of the Convert Module',['../convert_module.html',1,'lib_convert']]],
  ['definition_20of_20the_20core_20module_41',['Definition of the Core Module',['../core_module.html',1,'lib_core']]],
  ['definition_20of_20the_20editor_20module_42',['Definition of the Editor Module',['../editor_module.html',1,'lib_editor']]],
  ['definition_20of_20the_20email_20module_43',['Definition of the Email Module',['../email_module.html',1,'lib_email']]],
  ['definition_20of_20the_20envelope_20module_44',['Definition of the Envelope Module',['../envelope_module.html',1,'lib_envelope']]],
  ['definition_20of_20the_20expando_20module_45',['Definition of the Expando Module',['../expando_module.html',1,'lib_expando']]],
  ['definition_20of_20the_20gui_20module_46',['Definition of the Gui Module',['../gui_module.html',1,'lib_gui']]],
  ['definition_20of_20the_20hcache_20module_47',['Definition of the Hcache Module',['../hc_module.html',1,'lib_hcache']]],
  ['definition_20of_20the_20helpbar_20module_48',['Definition of the Helpbar Module',['../helpbar_module.html',1,'lib_helpbar']]],
  ['definition_20of_20the_20history_20module_49',['Definition of the History Module',['../history_module.html',1,'lib_history']]],
  ['definition_20of_20the_20hooks_20module_50',['Definition of the Hooks Module',['../hooks_module.html',1,'lib_hooks']]],
  ['definition_20of_20the_20imap_20module_51',['Definition of the Imap Module',['../imap_module.html',1,'lib_imap']]],
  ['definition_20of_20the_20index_20module_52',['Definition of the Index Module',['../index_module.html',1,'lib_index']]],
  ['definition_20of_20the_20key_20module_53',['Definition of the Key Module',['../key_module.html',1,'lib_key']]],
  ['definition_20of_20the_20lua_20module_54',['Definition of the Lua Module',['../lua_module.html',1,'lib_lua']]],
  ['definition_20of_20the_20maildir_20module_55',['Definition of the Maildir Module',['../maildir_module.html',1,'lib_maildir']]],
  ['definition_20of_20the_20main_20module_56',['Definition of the Main Module',['../main_module.html',1,'index']]],
  ['definition_20of_20the_20mbox_20module_57',['Definition of the Mbox Module',['../mbox_module.html',1,'lib_mbox']]],
  ['definition_20of_20the_20menu_20module_58',['Definition of the Menu Module',['../menu_module.html',1,'lib_menu']]],
  ['definition_20of_20the_20mh_20module_59',['Definition of the Mh Module',['../mh_module.html',1,'lib_mh']]],
  ['definition_20of_20the_20mutt_20module_60',['Definition of the Mutt Module',['../mutt_module.html',1,'lib_mutt']]],
  ['definition_20of_20the_20ncrypt_20module_61',['Definition of the Ncrypt Module',['../ncrypt_module.html',1,'lib_ncrypt']]],
  ['definition_20of_20the_20nntp_20module_62',['Definition of the Nntp Module',['../nntp_module.html',1,'lib_nntp']]],
  ['definition_20of_20the_20notmuch_20module_63',['Definition of the Notmuch Module',['../nm_module.html',1,'lib_notmuch']]],
  ['definition_20of_20the_20pager_20module_64',['Definition of the Pager Module',['../pager_module.html',1,'lib_pager']]],
  ['definition_20of_20the_20parse_20module_65',['Definition of the Parse Module',['../parse_module.html',1,'lib_parse']]],
  ['definition_20of_20the_20pattern_20module_66',['Definition of the Pattern Module',['../pattern_module.html',1,'lib_pattern']]],
  ['definition_20of_20the_20pop_20module_67',['Definition of the Pop Module',['../pop_module.html',1,'lib_pop']]],
  ['definition_20of_20the_20postpone_20module_68',['Definition of the Postpone Module',['../postpone_module.html',1,'lib_postpone']]],
  ['definition_20of_20the_20progress_20module_69',['Definition of the Progress Module',['../progress_module.html',1,'lib_progress']]],
  ['definition_20of_20the_20question_20module_70',['Definition of the Question Module',['../question_module.html',1,'lib_question']]],
  ['definition_20of_20the_20send_20module_71',['Definition of the Send Module',['../send_module.html',1,'lib_send']]],
  ['definition_20of_20the_20sidebar_20module_72',['Definition of the Sidebar Module',['../sidebar_module.html',1,'lib_sidebar']]],
  ['definition_20of_20the_20store_20module_73',['Definition of the Store Module',['../store_module.html',1,'lib_store']]],
  ['definitions_74',['definitions',['../alias_expando.html',1,'Alias Expando definitions'],['../compose_expando.html',1,'Alias Expando definitions'],['../attach_expando.html',1,'Attach Expando definitions'],['../autocrypt_expando.html',1,'Autocrypt Expando definitions'],['../browser_expando.html',1,'Browser Expando definitions'],['../compmbox_expando.html',1,'Compress Expando definitions'],['../send_expando_greeting.html',1,'Greeting Expando definitions'],['../history_expando.html',1,'History Expando definitions'],['../send_expando_msgid.html',1,'Message Id Expando definitions'],['../ncrypt_expando_command.html',1,'Ncrypt Expando definitions'],['../ncrypt_expando_gpgme.html',1,'Ncrypt Expando definitions'],['../ncrypt_expando_pgp.html',1,'Ncrypt Expando definitions'],['../ncrypt_expando_smime.html',1,'Ncrypt Expando definitions'],['../pattern_flags.html',1,'Pattern definitions'],['../pattern_expando.html',1,'Pattern Expando definitions'],['../sidebar_expando.html',1,'Sidebar Expando definitions']]],
  ['definitions_20of_20config_20variables_75',['Definitions of config variables',['../neo_mutt_config.html',1,'index']]],
  ['definitions_20of_20user_20functions_76',['Definitions of user functions',['../gui_functions.html',1,'lib_gui']]],
  ['details_20of_20an_20expando_20tree_77',['Dump the details of an Expando Tree',['../expando_serial.html',1,'lib_expando']]],
  ['dialog_78',['Dialog',['../alias_dlg_alias.html',1,'Address Book Dialog'],['../alias_dlg_query.html',1,'Address Query Dialog'],['../attach_dlg_attach.html',1,'Attachment Selection Dialog'],['../conn_dlg_verifycert.html',1,'Certificate Verification Dialog'],['../compose_dlg_compose.html',1,'Compose Email Dialog'],['../browser_dlg_browser.html',1,'File/Mailbox Browser Dialog'],['../crypt_dlg_gpgme.html',1,'GPGME Key Selection Dialog'],['../history_dlg_history.html',1,'History Selection Dialog'],['../index_dlg_index.html',1,'Index Dialog'],['../pager_dlg_pager.html',1,'Pager Dialog'],['../pattern_dlg_pattern.html',1,'Pattern Selection Dialog'],['../crypt_dlg_pgp.html',1,'PGP Key Selection Dialog'],['../postpone_dlg_postpone.html',1,'Postponed Email Selection Dialog'],['../gui_simple.html',1,'Simple Dialog'],['../pager_dopager.html',1,'Simple Pager Dialog'],['../crypt_dlg_smime.html',1,'SMIME Key Selection Dialog']]],
  ['dialog_79',['Autocrypt account dialog',['../autocrypt_dlg_autocrypt.html',1,'lib_autocrypt']]],
  ['dialog_20windows_80',['Dialog Windows',['../gui_dialog.html',1,'lib_gui']]],
  ['dialogs_81',['Shared code for alias dialogs',['../alias_gui.html',1,'lib_alias']]],
  ['different_20character_20encodings_82',['Conversion between different character encodings',['../mutt_charset.html',1,'lib_mutt']]],
  ['dispatcher_83',['Logging Dispatcher',['../mutt_logging.html',1,'lib_mutt']]],
  ['dispatcher_20of_20functions_84',['Dispatcher of functions',['../core_dispatcher.html',1,'lib_core']]],
  ['display_85',['Pager Display',['../pager_display.html',1,'lib_pager']]],
  ['display_20a_20user_20configurable_20status_20line_86',['display a user configurable status line',['../index_expando_status.html',1,'GUI display a user-configurable status line'],['../index_status.html',1,'GUI display a user-configurable status line']]],
  ['display_20email_20content_87',['Decide how to display email content',['../neo_handler.html',1,'index']]],
  ['display_20in_20the_20pager_88',['Process a message for display in the pager',['../pager_message.html',1,'lib_pager']]],
  ['display_20it_89',['Generate the help-page and GUI display it',['../neo_help.html',1,'index']]],
  ['display_20the_20mailboxes_20in_20a_20side_20panel_90',['GUI display the mailboxes in a side panel',['../sidebar_sidebar.html',1,'lib_sidebar']]],
  ['display_20usage_20information_20for_20neomutt_91',['Display Usage Information for NeoMutt',['../neo_usage.html',1,'index']]],
  ['display_20version_20and_20copyright_20about_20neomutt_92',['Display version and copyright about NeoMutt',['../neo_version.html',1,'index']]],
  ['dns_20lookups_93',['DNS lookups',['../conn_getdomain.html',1,'lib_conn']]],
  ['docs_94',['Code Docs',['../index.html',1,'']]],
  ['domain_20names_95',['International domain names',['../addr_idna.html',1,'lib_address']]],
  ['dot_20file_96',['GraphViz dot file',['../debug_graphviz.html',1,'lib_debug']]],
  ['drawing_20code_97',['Window drawing code',['../gui_curs_lib.html',1,'lib_gui']]],
  ['dump_20all_20notifications_98',['Dump all notifications',['../debug_notify.html',1,'lib_debug']]],
  ['dump_20all_20the_20config_99',['Dump all the config',['../config_dump.html',1,'lib_config']]],
  ['dump_20an_20email_100',['Dump an Email',['../debug_email.html',1,'lib_debug']]],
  ['dump_20command_101',['Colour Dump Command',['../color_dump.html',1,'lib_color']]],
  ['dump_20key_20bindings_102',['Dump key bindings',['../key_dump.html',1,'lib_key']]],
  ['dump_20keybindings_103',['Dump keybindings',['../debug_keymap.html',1,'lib_debug']]],
  ['dump_20the_20details_20of_20an_20expando_20tree_104',['Dump the details of an Expando Tree',['../expando_serial.html',1,'lib_expando']]],
  ['dump_20the_20hooks_20to_20the_20pager_105',['Dump the Hooks to the Pager',['../hooks_dump.html',1,'lib_hooks']]],
  ['dump_20the_20windows_106',['Dump the Windows',['../debug_window.html',1,'lib_debug']]],
  ['duplicate_20the_20structure_20of_20an_20entire_20email_107',['Duplicate the structure of an entire email',['../neo_copy.html',1,'index']]]
];
