var searchData=
[
  ['packets_0',['Parse PGP data packets',['../crypt_pgppacket.html',1,'lib_ncrypt']]],
  ['padding_20node_1',['Padding Node',['../expando_node_padding.html',1,'lib_expando']]],
  ['page_20and_20gui_20display_20it_2',['Generate the help-page and GUI display it',['../neo_help.html',1,'index']]],
  ['pager_3',['Pager',['../hooks_dump.html',1,'Dump the Hooks to the Pager'],['../lib_pager.html',1,'Pager'],['../pager_private_data.html',1,'Private state data for the Pager']]],
  ['pager_4',['Process a message for display in the pager',['../pager_message.html',1,'lib_pager']]],
  ['pager_20bar_5',['Pager Bar',['../pager_pbar.html',1,'lib_pager']]],
  ['pager_20debugging_6',['Pager Debugging',['../debug_pager.html',1,'lib_debug']]],
  ['pager_20dialog_7',['Pager Dialog',['../pager_dlg_pager.html',1,'Pager Dialog'],['../pager_dopager.html',1,'Simple Pager Dialog']]],
  ['pager_20display_8',['Pager Display',['../pager_display.html',1,'lib_pager']]],
  ['pager_20functions_9',['Pager functions',['../pager_functions.html',1,'lib_pager']]],
  ['pager_20panel_10',['Pager Panel',['../pager_ppanel.html',1,'lib_pager']]],
  ['pager_20window_11',['Pager Window',['../pager_pager.html',1,'lib_pager']]],
  ['paint_20the_20menu_12',['Paint the Menu',['../menu_draw.html',1,'lib_menu']]],
  ['panel_13',['Panel',['../index_ipanel.html',1,'Index Panel'],['../pager_ppanel.html',1,'Pager Panel']]],
  ['panel_14',['GUI display the mailboxes in a side panel',['../sidebar_sidebar.html',1,'lib_sidebar']]],
  ['parse_20a_20number_20in_20a_20string_15',['Parse a number in a string',['../mutt_atoi.html',1,'lib_mutt']]],
  ['parse_20alternate_20commands_16',['Parse Alternate Commands',['../commands_alternates.html',1,'lib_command']]],
  ['parse_20ansi_20sequences_17',['Parse ANSI Sequences',['../color_parse_ansi.html',1,'lib_color']]],
  ['parse_20colour_20commands_18',['Parse colour commands',['../color_commands.html',1,'Parse colour commands'],['../color_parse_color.html',1,'Parse colour commands']]],
  ['parse_20commands_20in_20a_20config_20file_19',['Functions to parse commands in a config file',['../parse_dump.html',1,'lib_parse']]],
  ['parse_20expando_20string_20',['Parse Expando string',['../lib_expando.html',1,'']]],
  ['parse_20group_20lists_20commands_21',['Parse Group/Lists Commands',['../commands_group.html',1,'lib_command']]],
  ['parse_20ifdef_20commands_22',['Parse Ifdef Commands',['../commands_ifdef.html',1,'lib_command']]],
  ['parse_20ignore_20commands_23',['Parse Ignore Commands',['../commands_ignore.html',1,'lib_command']]],
  ['parse_20key_20binding_20commands_24',['Parse key binding commands',['../key_commands.html',1,'lib_key']]],
  ['parse_20lines_20from_20a_20config_20file_25',['Parse lines from a config file',['../parse_rc.html',1,'lib_parse']]],
  ['parse_20mailboxes_20commands_26',['Parse Mailboxes Commands',['../commands_mailboxes.html',1,'lib_command']]],
  ['parse_20my_5fhdr_20commands_27',['Parse My_hdr Commands',['../commands_my_hdr.html',1,'lib_command']]],
  ['parse_20objects_28',['Parse objects',['../cli_objects.html',1,'lib_cli']]],
  ['parse_20pgp_20data_20packets_29',['Parse PGP data packets',['../crypt_pgppacket.html',1,'lib_ncrypt']]],
  ['parse_20setenv_20commands_30',['Parse Setenv Commands',['../commands_setenv.html',1,'lib_command']]],
  ['parse_20simple_20commands_31',['Parse Simple Commands',['../commands_parse.html',1,'lib_command']]],
  ['parse_20source_20commands_32',['Parse Source Commands',['../commands_source.html',1,'lib_command']]],
  ['parse_20spam_20commands_33',['Parse Spam Commands',['../commands_spam.html',1,'lib_command']]],
  ['parse_20stailq_20commands_34',['Parse Stailq Commands',['../commands_stailq.html',1,'lib_command']]],
  ['parse_20subjectrx_20commands_35',['Parse Subjectrx Commands',['../commands_subjectrx.html',1,'lib_command']]],
  ['parse_20tags_20commands_36',['Parse Tags Commands',['../commands_tags.html',1,'lib_command']]],
  ['parse_20the_20command_20line_37',['Parse the Command Line',['../lib_cli.html',1,'Parse the Command Line'],['../cli_parse.html',1,'Parse the Command Line']]],
  ['parse_20the_20output_20of_20cli_20pgp_20program_38',['Parse the output of CLI PGP program',['../crypt_gnupg.html',1,'lib_ncrypt']]],
  ['parse_20the_20set_20command_39',['Parse the &apos;set&apos; command',['../parse_set.html',1,'lib_parse']]],
  ['parse_20url_20schemes_40',['Parse URL schemes',['../email_url.html',1,'lib_email']]],
  ['parse_20user_20defined_20hooks_41',['Parse user-defined Hooks',['../hooks_parse.html',1,'lib_hooks']]],
  ['parsed_20expando_42',['Parsed Expando',['../expando_expando.html',1,'lib_expando']]],
  ['parser_43',['Text parser',['../parse_extract.html',1,'lib_parse']]],
  ['parsing_44',['Expando Parsing',['../expando_parse.html',1,'lib_expando']]],
  ['parsing_45',['Color and attribute parsing',['../color_color.html',1,'lib_color']]],
  ['parsing_20code_46',['Email parsing code',['../email_parse.html',1,'lib_email']]],
  ['parsing_20functions_47',['Text parsing functions',['../lib_parse.html',1,'']]],
  ['parsing_20strings_48',['Helper object for storing and parsing strings',['../mutt_buffer.html',1,'lib_mutt']]],
  ['part_49',['Attributes for a MIME part',['../email_parameter.html',1,'lib_email']]],
  ['pass_20files_20through_20external_20commands_20filters_50',['Pass files through external commands (filters)',['../mutt_filter.html',1,'lib_mutt']]],
  ['path_51',['Type: Path',['../config_path.html',1,'lib_config']]],
  ['path_20handling_52',['Maildir Path handling',['../maildir_path.html',1,'lib_maildir']]],
  ['path_20manipulation_20functions_53',['Path manipulation functions',['../mutt_path.html',1,'lib_mutt']]],
  ['pattern_54',['Pattern',['../pattern_compile.html',1,'Compile a Pattern'],['../pattern_exec.html',1,'Execute a Pattern'],['../lib_pattern.html',1,'Pattern']]],
  ['pattern_20auto_20completion_55',['Pattern Auto-Completion',['../pattern_complete.html',1,'lib_pattern']]],
  ['pattern_20data_56',['Private Pattern Data',['../pattern_pattern_data.html',1,'lib_pattern']]],
  ['pattern_20definitions_57',['Pattern definitions',['../pattern_flags.html',1,'lib_pattern']]],
  ['pattern_20expando_20definitions_58',['Pattern Expando definitions',['../pattern_expando.html',1,'lib_pattern']]],
  ['pattern_20functions_59',['Pattern functions',['../pattern_functions.html',1,'lib_pattern']]],
  ['pattern_20handling_20for_20messages_60',['Pattern handling for messages',['../pattern_message.html',1,'lib_pattern']]],
  ['pattern_20selection_20dialog_61',['Pattern Selection Dialog',['../pattern_dlg_pattern.html',1,'lib_pattern']]],
  ['patterns_20to_20emails_62',['Match patterns to emails',['../pattern_pattern.html',1,'lib_pattern']]],
  ['pgp_63',['PGP',['../crypt_crypt_mod_pgp.html',1,'Wrappers for calls to CLI PGP'],['../crypt_crypt_mod_pgp_gpgme.html',1,'Wrappers for calls to GPGME PGP']]],
  ['pgp_20data_20packets_64',['Parse PGP data packets',['../crypt_pgppacket.html',1,'lib_ncrypt']]],
  ['pgp_20functions_65',['Pgp functions',['../pgp_functions.html',1,'lib_ncrypt']]],
  ['pgp_20helper_20routines_66',['Misc PGP helper routines',['../crypt_pgplib.html',1,'lib_ncrypt']]],
  ['pgp_20key_20management_20routines_67',['PGP key management routines',['../crypt_pgpkey.html',1,'lib_ncrypt']]],
  ['pgp_20key_20selection_20dialog_68',['PGP Key Selection Dialog',['../crypt_dlg_pgp.html',1,'lib_ncrypt']]],
  ['pgp_20key_20sorting_69',['PGP Key Sorting',['../crypt_sort_pgp.html',1,'lib_ncrypt']]],
  ['pgp_20program_70',['PGP program',['../crypt_gnupg.html',1,'Parse the output of CLI PGP program'],['../crypt_pgpinvoke.html',1,'Wrapper around calls to external PGP program']]],
  ['pgp_20sign_20encrypt_20check_20routines_71',['PGP sign, encrypt, check routines',['../crypt_pgp.html',1,'lib_ncrypt']]],
  ['pgp_20signature_72',['Identify the hash algorithm from a PGP signature',['../crypt_pgpmicalg.html',1,'lib_ncrypt']]],
  ['pgp_20smime_20calls_20to_20gpgme_73',['Wrapper for PGP/SMIME calls to GPGME',['../crypt_crypt_gpgme.html',1,'lib_ncrypt']]],
  ['pgp_20smime_20functions_74',['PGP/Smime functions',['../crypt_functions.html',1,'lib_ncrypt']]],
  ['piped_20to_20external_20commands_75',['Manage where the email is piped to external commands',['../neo_external.html',1,'index']]],
  ['plain_20authentication_76',['Plain authentication',['../imap_auth_plain.html',1,'lib_imap']]],
  ['plain_20authentication_77',['SASL plain authentication',['../conn_sasl_plain.html',1,'lib_conn']]],
  ['pool_20of_20buffers_78',['A global pool of Buffers',['../mutt_pool.html',1,'lib_mutt']]],
  ['pop_79',['Pop',['../lib_pop.html',1,'']]],
  ['pop_20and_20imap_80',['ConnAccount object used by POP and IMAP',['../conn_mutt_account.html',1,'lib_conn']]],
  ['pop_20authentication_81',['POP authentication',['../pop_auth.html',1,'lib_pop']]],
  ['pop_20helper_20routines_82',['POP helper routines',['../pop_lib.html',1,'lib_pop']]],
  ['pop_20network_20mailbox_83',['POP network mailbox',['../pop_pop.html',1,'lib_pop']]],
  ['pop_20specific_20account_20data_84',['Pop-specific Account data',['../pop_adata.html',1,'lib_pop']]],
  ['pop_20specific_20email_20data_85',['Pop-specific Email data',['../pop_edata.html',1,'lib_pop']]],
  ['position_20selection_86',['Change the Menu&apos;s position/selection',['../menu_move.html',1,'lib_menu']]],
  ['postponed_20email_87',['Postponed Email',['../postpone_postpone.html',1,'lib_postpone']]],
  ['postponed_20email_20selection_20dialog_88',['Postponed Email Selection Dialog',['../postpone_dlg_postpone.html',1,'lib_postpone']]],
  ['postponed_20emails_89',['Postponed Emails',['../lib_postpone.html',1,'']]],
  ['postponed_20emails_20functions_90',['Postponed Emails Functions',['../postpone_functions.html',1,'lib_postpone']]],
  ['precompiled_20predefined_20regular_20expressions_91',['Manage precompiled / predefined regular expressions',['../mutt_prex.html',1,'lib_mutt']]],
  ['predefined_20regular_20expressions_92',['Manage precompiled / predefined regular expressions',['../mutt_prex.html',1,'lib_mutt']]],
  ['prepare_20an_20email_20to_20be_20edited_93',['Prepare an email to be edited',['../neo_editmsg.html',1,'index']]],
  ['prepare_20and_20send_20an_20email_94',['Prepare and send an email',['../send_send.html',1,'lib_send']]],
  ['present_20the_20user_20with_20a_20selectable_20list_95',['GUI present the user with a selectable list',['../menu_menu.html',1,'lib_menu']]],
  ['preview_20window_96',['Message Preview Window',['../compose_preview.html',1,'lib_compose']]],
  ['private_20autocrypt_20data_97',['Private Autocrypt Data',['../autocrypt_autocrypt_data.html',1,'lib_autocrypt']]],
  ['private_20copy_20of_20the_20environment_20variables_98',['Private copy of the environment variables',['../mutt_envlist.html',1,'lib_mutt']]],
  ['private_20data_99',['Message Window private data',['../gui_msgwin_wdata.html',1,'lib_gui']]],
  ['private_20data_20for_20the_20browser_100',['Private data for the Browser',['../browser_private_data.html',1,'lib_browser']]],
  ['private_20data_20for_20the_20index_101',['Private data for the Index',['../index_private_data.html',1,'lib_index']]],
  ['private_20pattern_20data_102',['Private Pattern Data',['../pattern_pattern_data.html',1,'lib_pattern']]],
  ['private_20state_20data_20for_20attachments_103',['Private state data for Attachments',['../attach_private_data.html',1,'lib_attach']]],
  ['private_20state_20data_20for_20the_20pager_104',['Private state data for the Pager',['../pager_private_data.html',1,'lib_pager']]],
  ['process_20a_20message_20for_20display_20in_20the_20pager_105',['Process a message for display in the pager',['../pager_message.html',1,'lib_pager']]],
  ['processing_106',['Command line processing',['../neo_main.html',1,'index']]],
  ['processing_20files_107',['Keep track when processing files',['../mutt_state.html',1,'lib_mutt']]],
  ['processing_20routines_20to_20generate_20the_20mail_20index_108',['String processing routines to generate the mail index',['../index_expando_index.html',1,'lib_index']]],
  ['program_109',['program',['../crypt_gnupg.html',1,'Parse the output of CLI PGP program'],['../crypt_pgpinvoke.html',1,'Wrapper around calls to external PGP program']]],
  ['program_20now_110',['Leave the program NOW',['../mutt_exit.html',1,'lib_mutt']]],
  ['programs_111',['Execute external programs',['../neo_system.html',1,'index']]],
  ['progress_20bar_112',['Progress Bar',['../progress_config.html',1,'Config used by the Progress Bar'],['../lib_progress.html',1,'Progress Bar'],['../progress_progress.html',1,'Progress Bar']]],
  ['progress_20bar_20window_113',['Progress Bar Window',['../progress_window.html',1,'lib_progress']]],
  ['progress_20bar_20window_20data_114',['Progress Bar Window Data',['../progress_wdata.html',1,'lib_progress']]]
];
