var searchData=
[
  ['mailbox_20browser_0',['Mailbox browser',['../imap_browse.html',1,'lib_imap']]],
  ['mailbox_20browser_1',['Mailbox Browser',['../lib_browser.html',1,'']]],
  ['mailbox_20helper_20functions_2',['Mailbox helper functions',['../neo_mutt_mailbox.html',1,'index']]],
  ['mailbox_20multiplexor_3',['Mailbox multiplexor',['../neo_mx.html',1,'index']]],
  ['mailbox_20object_4',['Mailbox object',['../core_mailbox.html',1,'lib_core']]],
  ['maildir_20email_20helper_5',['Maildir Email helper',['../maildir_mdemail.html',1,'lib_maildir']]],
  ['maildir_20local_20mailbox_20type_6',['Maildir local mailbox type',['../maildir_maildir.html',1,'lib_maildir']]],
  ['maildir_20mailbox_7',['Maildir Mailbox',['../lib_maildir.html',1,'']]],
  ['maildir_2dspecific_20email_20data_8',['Maildir-specific Email data',['../maildir_edata.html',1,'lib_maildir']]],
  ['maildir_2dspecific_20mailbox_20data_9',['Maildir-specific Mailbox data',['../maildir_mdata.html',1,'lib_maildir']]],
  ['manage_20precompiled_20_2f_20predefined_20regular_20expressions_10',['Manage precompiled / predefined regular expressions',['../mutt_prex.html',1,'lib_mutt']]],
  ['manage_20regular_20expressions_11',['Manage regular expressions',['../mutt_regex.html',1,'lib_mutt']]],
  ['manage_20where_20the_20email_20is_20piped_20to_20external_20commands_12',['Manage where the email is piped to external commands',['../neo_external.html',1,'index']]],
  ['manipulate_20an_20email_27s_20header_13',['Manipulate an email&apos;s header',['../neo_mutt_header.html',1,'index']]],
  ['manipulate_20multipart_20emails_14',['Manipulate multipart Emails',['../send_multipart.html',1,'lib_send']]],
  ['manipulate_20the_20flags_20in_20an_20email_20header_15',['Manipulate the flags in an email header',['../neo_flags.html',1,'index']]],
  ['map_20between_20a_20string_20and_20a_20constant_16',['Map between a string and a constant',['../mutt_mapping.html',1,'lib_mutt']]],
  ['match_20patterns_20to_20emails_17',['Match patterns to emails',['../pattern_pattern.html',1,'lib_pattern']]],
  ['mbox_18',['Mbox',['../lib_mbox.html',1,'']]],
  ['mbox_20local_20mailbox_20type_19',['Mbox local mailbox type',['../mbox_mbox.html',1,'lib_mbox']]],
  ['memory_20management_20wrappers_20',['Memory management wrappers',['../mutt_memory.html',1,'lib_mutt']]],
  ['menu_21',['Menu',['../lib_menu.html',1,'']]],
  ['menu_20functions_22',['Menu functions',['../menu_functions.html',1,'lib_menu']]],
  ['menu_20notification_20observers_23',['Menu notification observers',['../menu_observer.html',1,'lib_menu']]],
  ['menu_20types_24',['Menu types',['../menu_type.html',1,'lib_menu']]],
  ['merged_20colours_25',['Merged colours',['../color_merge.html',1,'lib_color']]],
  ['message_20container_26',['Message Container',['../gui_msgcont.html',1,'lib_gui']]],
  ['message_20window_27',['Message Window',['../gui_msgwin.html',1,'lib_gui']]],
  ['message_20window_20private_20data_28',['Message Window private data',['../gui_msgwin_wdata.html',1,'lib_gui']]],
  ['mh_20email_20helper_29',['Mh Email helper',['../mh_mdemail.html',1,'lib_mh']]],
  ['mh_20local_20mailbox_20type_30',['MH local mailbox type',['../mh_mh.html',1,'lib_mh']]],
  ['mh_20mailbox_31',['Mh Mailbox',['../lib_mh.html',1,'']]],
  ['mh_20mailbox_20sequences_32',['MH Mailbox Sequences',['../mh_sequence.html',1,'lib_mh']]],
  ['mh_20shared_20functions_33',['MH shared functions',['../mh_shared.html',1,'lib_mh']]],
  ['mh_2dspecific_20mailbox_20data_34',['Mh-specific Mailbox data',['../mh_mdata.html',1,'lib_mh']]],
  ['misc_20pgp_20helper_20routines_35',['Misc PGP helper routines',['../crypt_pgplib.html',1,'lib_ncrypt']]],
  ['miscellaneous_20functions_20for_20sending_20an_20email_36',['Miscellaneous functions for sending an email',['../send_sendlib.html',1,'lib_send']]],
  ['mixmaster_37',['Mixmaster',['../lib_mixmaster.html',1,'']]],
  ['mixmaster_20chain_20data_38',['Mixmaster Chain Data',['../mixmaster_chain_data.html',1,'lib_mixmaster']]],
  ['mixmaster_20chain_20window_39',['Mixmaster Chain Window',['../mixmaster_win_chain.html',1,'lib_mixmaster']]],
  ['mixmaster_20functions_40',['Mixmaster functions',['../mixmaster_functions.html',1,'lib_mixmaster']]],
  ['mixmaster_20hosts_20window_41',['Mixmaster Hosts Window',['../mixmaster_win_hosts.html',1,'lib_mixmaster']]],
  ['mixmaster_20remailer_42',['Mixmaster Remailer',['../mixmaster_mixmaster.html',1,'lib_mixmaster'],['../mixmaster_remailer.html',1,'lib_mixmaster']]],
  ['mixmaster_20remailer_20dialog_43',['Mixmaster Remailer Dialog',['../mixmaster_dlg_mixmaster.html',1,'lib_mixmaster']]],
  ['monitor_20files_20for_20changes_44',['Monitor files for changes',['../neo_monitor.html',1,'index']]],
  ['msn_20helper_20functions_45',['MSN helper functions',['../imap_msn.html',1,'lib_imap']]],
  ['multi_2dbyte_20string_20manipulation_20functions_46',['Multi-byte String manipulation functions',['../mutt_mbyte.html',1,'lib_mutt']]],
  ['mutt_47',['Mutt',['../lib_mutt.html',1,'']]]
];
