var searchData=
[
  ['lacking_20timegm_0',['For systems lacking timegm()',['../neo_timegm.html',1,'index']]],
  ['lacking_20wcscasecmp_1',['For systems lacking wcscasecmp()',['../neo_wcscasecmp.html',1,'index']]],
  ['leave_20the_20program_20now_2',['Leave the program NOW',['../mutt_exit.html',1,'lib_mutt']]],
  ['level_20socket_20code_3',['Low-level socket code',['../conn_raw.html',1,'lib_conn']]],
  ['level_20socket_20handling_4',['Low-level socket handling',['../conn_socket.html',1,'lib_conn']]],
  ['libbrowser_5',['Config used by libbrowser',['../browser_config.html',1,'lib_browser']]],
  ['libconn_6',['Config used by libconn',['../conn_config.html',1,'lib_conn']]],
  ['libmbox_7',['Config used by libmbox',['../mbox_config.html',1,'lib_mbox']]],
  ['libmenu_8',['Config used by libmenu',['../menu_config.html',1,'lib_menu']]],
  ['libncrypt_9',['Config used by libncrypt',['../crypt_config.html',1,'lib_ncrypt']]],
  ['libnntp_10',['Config used by libnntp',['../nntp_config.html',1,'lib_nntp']]],
  ['libnotmuch_11',['Config used by libnotmuch',['../nm_config.html',1,'lib_notmuch']]],
  ['libpager_12',['Config used by libpager',['../pager_config.html',1,'lib_pager']]],
  ['libpattern_13',['Config used by libpattern',['../pattern_config.html',1,'lib_pattern']]],
  ['libpop_14',['Config used by libpop',['../pop_config.html',1,'lib_pop']]],
  ['library_15',['library',['../attach_lib.html',1,'Attachment library'],['../email_config.html',1,'Config used by the Email library']]],
  ['libsend_16',['Config used by libsend',['../send_config.html',1,'lib_send']]],
  ['libsidebar_17',['Config used by libsidebar',['../sidebar_config.html',1,'lib_sidebar']]],
  ['lightning_20memory_20mapped_20database_20lmdb_18',['Lightning Memory-Mapped Database (LMDB)',['../store_lmdb.html',1,'lib_store']]],
  ['line_19',['Line',['../lib_cli.html',1,'Parse the Command Line'],['../cli_parse.html',1,'Parse the Command Line']]],
  ['line_20',['line',['../index_expando_status.html',1,'GUI display a user-configurable status line'],['../index_status.html',1,'GUI display a user-configurable status line']]],
  ['line_20processing_21',['Command line processing',['../neo_main.html',1,'index']]],
  ['linear_20array_20api_22',['Linear array API',['../mutt_array.html',1,'lib_mutt']]],
  ['lines_20from_20a_20config_20file_23',['Parse lines from a config file',['../parse_rc.html',1,'lib_parse']]],
  ['linked_20list_20type_24',['Singly-linked list type',['../mutt_list.html',1,'lib_mutt']]],
  ['list_25',['GUI present the user with a selectable list',['../menu_menu.html',1,'lib_menu']]],
  ['list_20of_20strings_26',['Type: List of strings',['../config_slist.html',1,'lib_config']]],
  ['list_20of_20strings_27',['A separated list of strings',['../mutt_slist.html',1,'lib_mutt']]],
  ['list_20type_28',['Singly-linked list type',['../mutt_list.html',1,'lib_mutt']]],
  ['lists_29',['Handle mailing lists',['../neo_maillist.html',1,'index']]],
  ['lists_20commands_30',['Parse Group/Lists Commands',['../commands_group.html',1,'lib_command']]],
  ['lmdb_31',['Lightning Memory-Mapped Database (LMDB)',['../store_lmdb.html',1,'lib_store']]],
  ['local_20email_32',['Local email',['../core_message.html',1,'lib_core']]],
  ['local_20mailbox_20type_33',['local mailbox type',['../maildir_maildir.html',1,'Maildir local mailbox type'],['../mbox_mbox.html',1,'Mbox local mailbox type'],['../mh_mh.html',1,'MH local mailbox type']]],
  ['log_20everything_20to_20the_20terminal_34',['Log everything to the terminal',['../debug_logging.html',1,'lib_debug']]],
  ['logging_35',['NeoMutt Logging',['../neo_mutt_logging.html',1,'index']]],
  ['logging_20dispatcher_36',['Logging Dispatcher',['../mutt_logging.html',1,'lib_mutt']]],
  ['login_20authentication_37',['Login authentication',['../imap_auth_login.html',1,'lib_imap']]],
  ['long_38',['Type: Long',['../config_long.html',1,'lib_config']]],
  ['lookups_39',['lookups',['../conn_getdomain.html',1,'DNS lookups'],['../alias_reverse.html',1,'Reverse Alias lookups']]],
  ['low_20level_20socket_20code_40',['Low-level socket code',['../conn_raw.html',1,'lib_conn']]],
  ['low_20level_20socket_20handling_41',['Low-level socket handling',['../conn_socket.html',1,'lib_conn']]],
  ['lua_20commands_42',['Lua Commands',['../lua_commands.html',1,'lib_lua']]],
  ['lua_20scripting_43',['Lua scripting',['../lib_lua.html',1,'Integrated Lua scripting'],['../lua_lua.html',1,'Integrated Lua scripting']]],
  ['lz4_20compression_44',['LZ4 compression',['../compress_lz4.html',1,'lib_compress']]]
];
