var searchData=
[
  ['pgp_20key_20selection_20dialog',['PGP key selection dialog',['../crypt_dlgpgp.html',1,'lib_ncrypt']]],
  ['parse_20the_20output_20of_20cli_20pgp_20program',['Parse the output of CLI PGP program',['../crypt_gnupg.html',1,'lib_ncrypt']]],
  ['pgp_20sign_2c_20encrypt_2c_20check_20routines',['PGP sign, encrypt, check routines',['../crypt_pgp.html',1,'lib_ncrypt']]],
  ['pgp_20key_20management_20routines',['PGP key management routines',['../crypt_pgpkey.html',1,'lib_ncrypt']]],
  ['parse_20pgp_20data_20packets',['Parse PGP data packets',['../crypt_pgppacket.html',1,'lib_ncrypt']]],
  ['parse_20and_20identify_20different_20url_20schemes',['Parse and identify different URL schemes',['../email_url.html',1,'lib_email']]],
  ['private_20data_20for_20the_20help_20bar',['Private data for the Help Bar',['../helpbar_wdata.html',1,'lib_helpbar']]],
  ['private_20state_20data_20for_20the_20index',['Private state data for the Index',['../index_private_data.html',1,'lib_index']]],
  ['pager_3a_20gui_20display_20contents_20of_20an_20email_20or_20help',['PAGER: GUI display contents of an email or help',['../lib_pager.html',1,'']]],
  ['pattern_3a_20match_20patterns_20to_20emails',['PATTERN: Match patterns to emails',['../lib_pattern.html',1,'']]],
  ['pop_3a_20network_20mailbox',['POP: Network mailbox',['../lib_pop.html',1,'']]],
  ['progress_3a_20progress_20bar',['PROGRESS: Progress Bar',['../lib_progress.html',1,'']]],
  ['paint_20the_20menu',['Paint the Menu',['../menu_draw.html',1,'lib_menu']]],
  ['private_20copy_20of_20the_20environment_20variables',['Private copy of the environment variables',['../mutt_envlist.html',1,'lib_mutt']]],
  ['pass_20files_20through_20external_20commands_20_28filters_29',['Pass files through external commands (filters)',['../mutt_filter.html',1,'lib_mutt']]],
  ['path_20manipulation_20functions',['Path manipulation functions',['../mutt_path.html',1,'lib_mutt']]],
  ['prepare_20an_20email_20to_20be_20edited',['Prepare an email to be edited',['../neo_editmsg.html',1,'index']]],
  ['parse_20and_20execute_20user_2ddefined_20hooks',['Parse and execute user-defined hooks',['../neo_hook.html',1,'index']]],
  ['pager_20bar',['Pager Bar',['../pager_pbar.html',1,'lib_pager']]],
  ['private_20state_20data_20for_20the_20pager',['Private state data for the Pager',['../pager_private_data.html',1,'lib_pager']]],
  ['pattern_20definitions',['Pattern definitions',['../pattern_flags.html',1,'lib_pattern']]],
  ['pop_2dspecific_20account_20data',['Pop-specific Account data',['../pop_adata.html',1,'lib_pop']]],
  ['pop_20authentication',['POP authentication',['../pop_auth.html',1,'lib_pop']]],
  ['pop_2dspecific_20email_20data',['Pop-specific Email data',['../pop_edata.html',1,'lib_pop']]],
  ['pop_20helper_20routines',['POP helper routines',['../pop_lib.html',1,'lib_pop']]],
  ['pop_20network_20mailbox',['POP network mailbox',['../pop_pop.html',1,'lib_pop']]],
  ['progress_20bar',['Progress Bar',['../progress_progress.html',1,'lib_progress']]],
  ['prepare_20and_20send_20an_20email',['Prepare and send an email',['../send_send.html',1,'lib_send']]]
];
