var searchData=
[
  ['mailbox_20browser_0',['Mailbox browser',['../imap_browse.html',1,'lib_imap']]],
  ['mailbox_20browser_1',['Mailbox Browser',['../lib_browser.html',1,'']]],
  ['mailbox_20helper_20functions_2',['Mailbox helper functions',['../neo_mutt_mailbox.html',1,'index']]],
  ['mailbox_20multiplexor_3',['Mailbox multiplexor',['../neo_mx.html',1,'index']]],
  ['mailbox_20object_4',['Mailbox object',['../core_mailbox.html',1,'lib_core']]],
  ['maildir_20email_20helper_5',['Maildir Email helper',['../maildir_mdemail.html',1,'lib_maildir']]],
  ['maildir_20local_20mailbox_20type_6',['Maildir local mailbox type',['../maildir_maildir.html',1,'lib_maildir']]],
  ['maildir_20mailbox_7',['Maildir Mailbox',['../lib_maildir.html',1,'']]],
  ['maildir_2dspecific_20email_20data_8',['Maildir-specific Email data',['../maildir_edata.html',1,'lib_maildir']]],
  ['maildir_2dspecific_20mailbox_20data_9',['Maildir-specific Mailbox data',['../maildir_mdata.html',1,'lib_maildir']]],
  ['maildir_2fmh_20local_20mailbox_20type_10',['Maildir/MH local mailbox type',['../maildir_shared.html',1,'lib_maildir']]],
  ['manage_20precompiled_20_2f_20predefined_20regular_20expressions_11',['Manage precompiled / predefined regular expressions',['../mutt_prex.html',1,'lib_mutt']]],
  ['manage_20regular_20expressions_12',['Manage regular expressions',['../mutt_regex.html',1,'lib_mutt']]],
  ['manage_20where_20the_20email_20is_20piped_20to_20external_20commands_13',['Manage where the email is piped to external commands',['../neo_external.html',1,'index']]],
  ['manipulate_20an_20email_27s_20header_14',['Manipulate an email&apos;s header',['../neo_mutt_header.html',1,'index']]],
  ['manipulate_20multipart_20emails_15',['Manipulate multipart Emails',['../send_multipart.html',1,'lib_send']]],
  ['manipulate_20the_20flags_20in_20an_20email_20header_16',['Manipulate the flags in an email header',['../neo_flags.html',1,'index']]],
  ['map_20between_20a_20string_20and_20a_20constant_17',['Map between a string and a constant',['../mutt_mapping.html',1,'lib_mutt']]],
  ['match_20patterns_20to_20emails_18',['Match patterns to emails',['../pattern_pattern.html',1,'lib_pattern']]],
  ['mbox_19',['Mbox',['../lib_mbox.html',1,'']]],
  ['mbox_20local_20mailbox_20type_20',['Mbox local mailbox type',['../mbox_mbox.html',1,'lib_mbox']]],
  ['memory_20management_20wrappers_21',['Memory management wrappers',['../mutt_memory.html',1,'lib_mutt']]],
  ['menu_22',['Menu',['../lib_menu.html',1,'']]],
  ['menu_20functions_23',['Menu functions',['../menu_functions.html',1,'lib_menu']]],
  ['menu_20notification_20observers_24',['Menu notification observers',['../menu_observer.html',1,'lib_menu']]],
  ['menu_20types_25',['Menu types',['../menu_type.html',1,'lib_menu']]],
  ['merged_20colours_26',['Merged colours',['../color_merge.html',1,'lib_color']]],
  ['message_20container_27',['Message Container',['../gui_msgcont.html',1,'lib_gui']]],
  ['message_20window_28',['Message Window',['../gui_msgwin.html',1,'lib_gui']]],
  ['message_20window_20private_20data_29',['Message Window private data',['../gui_msgwin_wdata.html',1,'lib_gui']]],
  ['mh_20local_20mailbox_20type_30',['MH local mailbox type',['../maildir_mh.html',1,'lib_maildir']]],
  ['mh_20mailbox_20sequences_31',['MH Mailbox Sequences',['../maildir_sequence.html',1,'lib_maildir']]],
  ['misc_20pgp_20helper_20routines_32',['Misc PGP helper routines',['../crypt_pgplib.html',1,'lib_ncrypt']]],
  ['miscellaneous_20functions_20for_20sending_20an_20email_33',['Miscellaneous functions for sending an email',['../send_sendlib.html',1,'lib_send']]],
  ['mixmaster_34',['Mixmaster',['../lib_mixmaster.html',1,'']]],
  ['mixmaster_20chain_20data_35',['Mixmaster Chain Data',['../mixmaster_chain_data.html',1,'lib_mixmaster']]],
  ['mixmaster_20chain_20window_36',['Mixmaster Chain Window',['../mixmaster_win_chain.html',1,'lib_mixmaster']]],
  ['mixmaster_20functions_37',['Mixmaster functions',['../mixmaster_functions.html',1,'lib_mixmaster']]],
  ['mixmaster_20hosts_20window_38',['Mixmaster Hosts Window',['../mixmaster_win_hosts.html',1,'lib_mixmaster']]],
  ['mixmaster_20remailer_39',['Mixmaster Remailer',['../mixmaster_mixmaster.html',1,'lib_mixmaster'],['../mixmaster_remailer.html',1,'lib_mixmaster']]],
  ['mixmaster_20remailer_20dialog_40',['Mixmaster Remailer Dialog',['../mixmaster_dlg_mixmaster.html',1,'lib_mixmaster']]],
  ['monitor_20files_20for_20changes_41',['Monitor files for changes',['../neo_monitor.html',1,'index']]],
  ['msn_20helper_20functions_42',['MSN helper functions',['../imap_msn.html',1,'lib_imap']]],
  ['multi_2dbyte_20string_20manipulation_20functions_43',['Multi-byte String manipulation functions',['../mutt_mbyte.html',1,'lib_mutt']]],
  ['mutt_44',['Mutt',['../lib_mutt.html',1,'']]]
];
